### ISSUE TITLE
how to get the R object from  java

### ISSUE THREAD

**Issue by AlexYoung757** [s-u/Rserve#103]
Hi Simon. 
 i have some troubles.
 as you now , using java to acess R scripts, the example as follow:

  R code :( myfun.R)
  data("mtcars")
  mtcar_new <- mtcars[sample(nrow(mtcars),50,replace=T),]
   
  Java  code:
      RConnection rc = new RConnection("your IP")
      rc.eval("source("/your path/myfun.R")");  
      
  now , how to get the R object mtcar_new  from  java?
  Thank you for your help , i am looking forward to your reply.

**Comment by dselivanov** [comment]
There are many examples of such simple things -  you can start stackoverflow. I suggest to close this issue.

**Comment by AlexYoung757** [comment]
ok ,thank you for your suggestions. can you give me some examples?

**Comment by s-u** [comment]
Um, `c.eval("mtcar_new")`?
