### ISSUE TITLE
Does Rserve only supports SSLv2.3?

### ISSUE THREAD

**Issue by 0golovatyi** [s-u/Rserve#107]
Looking at sources (https://github.com/s-u/Rserve/blob/484f5fedbaa906c9836464eff15dc896b11080f3/src/tls.c#L41 and https://github.com/s-u/Rserve/blob/484f5fedbaa906c9836464eff15dc896b11080f3/src/proxy/tls.c#L41) I discovered server methods set to SSLv2.3. Do I understand it correctly there's no TLS support?

**Comment by 0golovatyi** [comment]
Answering my own question.
Apparently `SSLv23_server_method()` means "the latest available" (which is TLS v1.2 in my case) and not "SSL v2.3".

**Comment by sirius93** [comment]
Hi @0golovatyi ,
I don't know if it is the right thread to ask this. but i was wondering if there is a way to enable TLS1.2 support for Rserve. I am struggling to find a proper way and any help would be much appreciated.

Thanks,
Nandan

**Comment by s-u** [comment]
Rserve supports whichever protocols your openssl provides. If you are missing any protocol support then it's likely because your openssl library is too old. Upgrade your openssl and recompile Rserve.

**Comment by NimoTh** [comment]
Is that the case also for version 1.7-3? Should TLS1.2 be supported with RServe 1.7-3?

**Comment by sirius93** [comment]
I think it should support tls 1.2
See if this might help, Something I put up once I was able to enable it for myself.

https://dev.to/sirius93/how-to-enable-t-l-s-1-2-in-r-serve-4ope
