### ISSUE TITLE
How do I build on Mac with crypt?

### ISSUE THREAD

**Issue by 0golovatyi** [s-u/Rserve#108]
When I build Rserve for Mac (with openssl) and configure it for TLS (cert and port) I see that handshake is not successful because of there's no crypt method.
I also noticed then when installing Rserv in R it can't find crypt library which I believe causes the issue above.
Was anyone able to solve or workaround the problem?

**Comment by s-u** [comment]
`libcrypt` is part of openssl, so do you have an incomplete installation? If in doubt, please post full error as well as full output of `config.log`

**Comment by jnegara** [comment]
I'm having the same issue. When I install using CRAN I get the following output:
`* installing *source* package ‘Rserve’ ...
** package ‘Rserve’ successfully unpacked and MD5 sums checked
checking whether to compile the server... yes
checking whether to compile the client... no
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for string.h... (cached) yes
checking for memory.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking for sys/types.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/un.h usability... yes
checking sys/un.h presence... yes
checking for sys/un.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking netinet/tcp.h usability... yes
checking netinet/tcp.h presence... yes
checking for netinet/tcp.h... yes
checking for an ANSI C-conforming const... yes
checking whether byte ordering is bigendian... no
checking whether time.h and sys/time.h may both be included... yes
checking for pid_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking return type of signal handlers... void
checking for memset... yes
checking for mkdir... yes
checking for rmdir... yes
checking for select... yes
checking for socket... yes
checking for srandomdev... yes
checking for library containing crypt... none required
checking crypt.h usability... no
checking crypt.h presence... no
checking for crypt.h... no
checking for socklen_t... yes
checking for connect... yes
checking whether to enable IPv6... no
checking for dlopen in -ldl... yes
checking openssl/rsa.h usability... yes
checking openssl/rsa.h presence... yes
checking for openssl/rsa.h... yes
checking for library containing RSA_generate_key... -lcrypto
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for library containing SSL_CTX_load_verify_locations... -lssl
configure: creating ./config.status
config.status: creating src/Makevars
config.status: creating src/client/cxx/Makefile
config.status: creating src/config.h
** libs
clang -I"/usr/local/Cellar/r/3.5.0_1/lib/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude    -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2  -c RSserver.c -o RSserver.o
clang -I"/usr/local/Cellar/r/3.5.0_1/lib/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude    -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2  -c Rserv.c -o Rserv.o
Rserv.c:2976:16: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
                                        if (fbufl < 0) fbufl = sfbufSize;
                                            ~~~~~ ^ ~
1 warning generated.
clang -I"/usr/local/Cellar/r/3.5.0_1/lib/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude    -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2  -c base64.c -o base64.o
clang -I"/usr/local/Cellar/r/3.5.0_1/lib/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude    -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2  -c http.c -o http.o
clang -I"/usr/local/Cellar/r/3.5.0_1/lib/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude    -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2  -c md5.c -o md5.o
clang -I"/usr/local/Cellar/r/3.5.0_1/lib/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude    -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2  -c oc.c -o oc.o
oc.c:72:11: warning: passing 'unsigned char [64]' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        sha1hash(rbuf, sizeof(rbuf) - 1, hash);
                 ^~~~
./sha1.h:4:27: note: passing argument to parameter 'buf' here
void sha1hash(const char *buf, int len, unsigned char hash[20]);
                          ^
1 warning generated.
clang -I"/usr/local/Cellar/r/3.5.0_1/lib/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude    -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2  -c qap_decode.c -o qap_decode.o
clang -I"/usr/local/Cellar/r/3.5.0_1/lib/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude    -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2  -c qap_encode.c -o qap_encode.o
clang -I"/usr/local/Cellar/r/3.5.0_1/lib/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude    -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2  -c rsio.c -o rsio.o
clang -I"/usr/local/Cellar/r/3.5.0_1/lib/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude    -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2  -c session.c -o session.o
clang -I"/usr/local/Cellar/r/3.5.0_1/lib/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude    -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2  -c sha1.c -o sha1.o
clang -I"/usr/local/Cellar/r/3.5.0_1/lib/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude    -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2  -c standalone.c -o standalone.o
clang -I"/usr/local/Cellar/r/3.5.0_1/lib/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude    -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2  -c tls.c -o tls.o
tls.c:41:15: warning: assigning to 'SSL_METHOD *' (aka 'struct ssl_method_st *') from 'const SSL_METHOD *' (aka 'const struct ssl_method_st *') discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    t->method = SSLv23_server_method();
              ^ ~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
clang -I"/usr/local/Cellar/r/3.5.0_1/lib/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude    -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2  -c websockets.c -o websockets.o
clang -I"/usr/local/Cellar/r/3.5.0_1/lib/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude    -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2  -c winembed.c -o winembed.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/usr/local/Cellar/r/3.5.0_1/lib/R/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -o Rserve.so RSserver.o Rserv.o base64.o http.o md5.o oc.o qap_decode.o qap_encode.o rsio.o session.o sha1.o standalone.o tls.o websockets.o winembed.o -lssl -lcrypto -ldl -L/usr/local/Cellar/r/3.5.0_1/lib/R/lib -lR -lintl -Wl,-framework -Wl,CoreFoundation
clang -DSTANDALONE_RSERVE -DDAEMON -I. -Iinclude -I"/usr/local/Cellar/r/3.5.0_1/lib/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude    -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include -g -O2  -DRSERVE_PKG -I. -Iinclude    -o Rserve standalone.c md5.c session.c qap_decode.c qap_encode.c sha1.c base64.c websockets.c RSserver.c tls.c http.c oc.c rsio.c -lssl -lcrypto -ldl    -L"/usr/local/Cellar/r/3.5.0_1/lib/R/lib" -lR -lintl -Wl,-framework -Wl,CoreFoundation -lssl -lcrypto -ldl  
In file included from standalone.c:6:
./Rserv.c:2976:16: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
                                        if (fbufl < 0) fbufl = sfbufSize;
                                            ~~~~~ ^ ~
1 warning generated.
tls.c:41:15: warning: assigning to 'SSL_METHOD *' (aka 'struct ssl_method_st *') from 'const SSL_METHOD *' (aka 'const struct ssl_method_st *') discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    t->method = SSLv23_server_method();
              ^ ~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
oc.c:72:11: warning: passing 'unsigned char [64]' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        sha1hash(rbuf, sizeof(rbuf) - 1, hash);
                 ^~~~
./sha1.h:4:27: note: passing argument to parameter 'buf' here
void sha1hash(const char *buf, int len, unsigned char hash[20]);
                          ^
1 warning generated.
clang -DSTANDALONE_RSERVE -DRSERV_DEBUG -DNODAEMON -I. -Iinclude -I"/usr/local/Cellar/r/3.5.0_1/lib/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude    -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2  -DRSERVE_PKG -I. -Iinclude    -o Rserve.dbg standalone.c md5.c session.c qap_decode.c qap_encode.c sha1.c base64.c websockets.c RSserver.c tls.c http.c oc.c rsio.c -lssl -lcrypto -ldl    -L"/usr/local/Cellar/r/3.5.0_1/lib/R/lib" -lR -lintl -Wl,-framework -Wl,CoreFoundation -lssl -lcrypto -ldl  
In file included from standalone.c:6:
./Rserv.c:2976:16: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
                                        if (fbufl < 0) fbufl = sfbufSize;
                                            ~~~~~ ^ ~
1 warning generated.
tls.c:41:15: warning: assigning to 'SSL_METHOD *' (aka 'struct ssl_method_st *') from 'const SSL_METHOD *' (aka 'const struct ssl_method_st *') discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    t->method = SSLv23_server_method();
              ^ ~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
oc.c:72:11: warning: passing 'unsigned char [64]' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        sha1hash(rbuf, sizeof(rbuf) - 1, hash);
                 ^~~~
./sha1.h:4:27: note: passing argument to parameter 'buf' here
void sha1hash(const char *buf, int len, unsigned char hash[20]);
                          ^
1 warning generated.
./mergefat Rserve "/usr/local/Cellar/r/3.5.0_1/lib/R/bin/Rserve"
./mergefat Rserve.dbg "/usr/local/Cellar/r/3.5.0_1/lib/R/bin/Rserve.dbg"
installing via 'install.libs.R' to /usr/local/lib/R/3.5/site-library/Rserve
generating debug symbols (dSYM)
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (Rserve)
`

I'm not finding a `config.log`, do you know where I should look?

**Comment by dselivanov** [comment]
Is it related to #99?

**Comment by jnegara** [comment]
It shouldn't be. I'm trying to eventually use an IPC connection, not HTTP.

When I run an Rserve instance with the following config file:
```
tls.key ~/cert/Rserve.key
tls.cert ~/cert/Rserve.crt
tls.port 4902
qap disable
```

my TLS handshake fails with the following output:
```
jnegara-mac:~ jnegara$ openssl s_client -connect localhost:4902 -servername localhost -tls1_2 -cert ~/cert/Rserve.crt -key ~/cert/Rserve.key
CONNECTED(00000003)
140735663068040:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:s3_pkt.c:1498:SSL alert number 40
140735663068040:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:s3_pkt.c:659:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1532471857
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```

I believe the reason it's failing is because when CRAN builds R it does not find `crypt.h` headers, so it does not compile with support for encryption. `crypt.h` is not available on mac, so I'm not exactly sure how to proceed.

**Comment by s-u** [comment]
No, it's unrelated. However, yes, `crypt.h` is no longer present on macOS even though the functions are available. I'll see if I can modify the check and proceed even if the headers don't exist.

**Comment by s-u** [comment]
Coming back to this - it's actually a user error. The config file is incorrect since you likely don't mean to use `~` literally - this not a shell, so you have to use the actual path to your home if that's what you intended to reference. Similarly to #127 it perhaps would help if Rserve would fail if the key/cert cannot be loaded to detect such user errors.
