### ISSUE TITLE
Rserve memory exhaustion - no mechanism to prevent out of memory

### ISSUE THREAD

**Issue by jacoblovatt1987** [s-u/Rserve#112]
Rserve doesn't seem to implement any kind of throttling/limiting of currency to prevent forking when this would exhaust memory.

Is this by design, and if so does this imply throttling/limiting concurrency needs to be implemented outside of Rserve?

**Comment by dselivanov** [comment]
duplicate #91 - use HAproxy or nginx if needed

**Comment by s-u** [comment]
Correct, Rserve doesn't provide any kind throttling (it only provides optional memory limits per session). Other than in control command mode the server keeps no track of spawned connections. It is recommended to use `nginx` or similar which have virtually no overhead and are very flexible in the way of configuration. Given the very dynamic nature of R, is it not clear how a practically reliable approach could be implemented beyond just connection count limits.
