### ISSUE TITLE
How can I build from source on ubuntu?

### ISSUE THREAD

**Issue by karlroberts** [s-u/Rserve#116]
Hi I want to try to use PullRequest #101 but it's not yet merged. But I'm afraid I have not been a c coder for a long time. please can you let me know or add a README how to build from source?

I have tried:- 
`sudo apt-get install libcurl4-openssl-dev`
in order to get past the `configure.ac:48: error: possibly undefined macro: AC_MSG_RESULT` error when running autoconf, which worked, but then I get as far as the following and i'm then stuck

```
$ aclocal
$ autoconf
$ automake --add-missing
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
automake: error: no 'Makefile.am' found for any configure output
```
Please add the missing README :-)

**Comment by s-u** [comment]
Please see the documentation on
http://rforge.net/Rserve

If you want to build from the checkout (as opposed the repo) you use
`sh mkdist`
to generate the package tar ball.
