### ISSUE TITLE
More thoughts on "long vectors not supported" problem in qap_encode.c

### ISSUE THREAD

**Issue by pzingg** [s-u/Rserve#117]
Apparently issue #102 was closed successfully, but I was wondering whether the code in the `getStorageSize` function could be made a little more bulletproof by avoiding the `XLENGTH` call altogether for types that don't use it. The current master branch does this:

```
int t = TYPEOF(x);
rlen_t tl = XLENGTH(x); /* although LENGTH can only be 32-bit use rlen_t to avoid downcasting */
```

I noticed that the value of `tl` is very large for `LISTSXP` and `SYMSXP` types. It turns out the length calculations in `getStorageSize` depend on `tl` only for a limited number of types (examine the case statements):

```
case CPLXSXP:
case REALSXP:
case INTSXP:
case LGLSXP:
case RAWSXP:
case STRSXP:
case EXPRSXP:
case VECSXP:
```

In releases 1.8.6 and previous, it was `tl = LENGTH(x);` (not `XLENGTH`) which was blowing up and producing the "long vectors not supported yet" error in issue #102. I read one bug report that said that this error was being thrown intermittently (hard to reproduce). My guess is that taking `LENGTH(x)` on a LISTSXP or SYMSXP type was overflowing the 32-bit limit, even though that `tl` value would never be used.

Perhaps it would be better/safer in the code to have this, not calling `XLENGTH` on types that don't need it:

```
int t = TYPEOF(x);
rlen_t tl = 0;
switch (t) {
case CPLXSXP:
case REALSXP:
case INTSXP:
case LGLSXP:
case RAWSXP:
case STRSXP:
case EXPRSXP:
case VECSXP:
case CHARSXP: /* tl not used for CHARSXP but value is useful for debugging */
  tl = XLENGTH(x); /* although LENGTH can only be 32-bit use rlen_t to avoid downcasting */
#if defined RSERV_DEBUG && ! (defined DEBUG_NO_STORAGE)
  printf("getStorageSize(%p,type=%d,len=%ld) ", (void*)x, t, tl);
#endif
  break;
default:
  /* tl not used for other types */
#if defined RSERV_DEBUG && ! (defined DEBUG_NO_STORAGE)
  printf("getStorageSize(%p,type=%d) ", (void*)x, t);
#endif
  break;
}
```

Feel free to ignore this issue if you feel that the problem raised in #102 has been completely resolved.

**Comment by s-u** [comment]
I think this has been resolved in the meantime.
