### ISSUE TITLE
Maximum buffer size

### ISSUE THREAD

**Issue by Milchreis** [s-u/Rserve#120]
Hi,

I use RServe in combination with RODBC to fetch data from database, process them in R and sending the results back to Java. Currently RServe stuck on working with large SQL result sets. In the taskmonitor I saw the problem starts ~ 1GB of RAM. The process is waiting for nothing and the RAM is still used.

The documentation says the SendBifferSize is limited to 1GB and maxsendbuf is unlimited on default. I changed both values with no effect.

Is it possible to change the limit?

**Settings:** 
RServe_1.8-6
R version 3.5.1
Platform: i686-pc-linux-gnu (32-bit)
Running under: Ubuntu 14.04.5 LT
Java 8 with org.rosuda.REngine.Rserve 1.8.1

**Comment by s-u** [comment]
`maxSendBuf` is by default unlimited, so that doesn't seem to be relevant here. Can you post a reproducible example?
