### ISSUE TITLE
Sometimes Rserve no response

### ISSUE THREAD

**Issue by ifo1999** [s-u/Rserve#123]
Hello I appreciate your help to make the webservice via your library
rserve is running in daemon at the linux OS
I use the rserve to receive the call from java
Sometimes java call the Rscript but had no response. From java side rconnection was succeed but via eval expression had no response. If it was successfully called I can see script printed from the log. When problems has occurred there was no log
And there was no heavy transaction
CPU and Memory was enough to serve
And there was empty folder in the tmp/Rserve like conn12xxxx
Could you give me the solution?

**Comment by manuelwaltschek** [comment]
Can you provide example code maybe a JUnit Test Case? What was the resulting REXP of eval()?

**Comment by ifo1999** [comment]
eval return nothing. It looks hanging.

**Comment by manuelwaltschek** [comment]
Can you provide code to reproduce this?

**Comment by s-u** [comment]
Nothing supplied to reproduce.
