### ISSUE TITLE
No path specified.eval failed with error code 65

### ISSUE THREAD

**Issue by gitbobo** [s-u/Rserve#126]
Using `Rserve/src/client/php/simple.php` to test Rserve.  
I got feedback as below:  

> No path specified.eval failed with error code 65
> eval failed with error code 0

I need some clue to find the reason,thanks in advance!

**Comment by s-u** [comment]
It means you didn't specify a path in the request (URL).

See the example code on how to use it - you are using the FastRWeb compatibility function but did not specify any path to serve. You can also use the test at the bottom instead if that's what you want to do ..

Note the PHP support is just an example -  if you want to use PHP there are more complete client libraries such as https://github.com/cturbelin/rserve-php
