### ISSUE TITLE
Is there new release for Rserve?

### ISSUE THREAD

**Issue by 0golovatyi** [s-u/Rserve#130]
I see there were relatively recent changes in the repo but the latest release available at https://github.com/s-u/Rserve/releases is 1.8.4. At the same time, https://www.rforge.net/Rserve/news.html mentions 1.8.6. Is the https://www.rforge.net/Rserve/files/ the only place where Rserve releases should be downloaded from?

**Comment by nmannheimer** [comment]
Any further information on this?

**Comment by s-u** [comment]
Please don't use GitHub "releases" - they don't work since the tar ball that GitHub creates is not a valid package. I have deleted the GH"releases" as to not confuse people.
