### ISSUE TITLE
install.packages('Rserve',,'http://www.rforge.net/') fails with undefined reference to `SSL_library_init' & 'SSLv23_server_method'

### ISSUE THREAD

**Issue by ZedekiahZhou** [s-u/Rserve#133]
**Ubuntu 18.04.2 LTS**
**R version 3.6.1**

**I am trying to install Rserve, but fails with error below.** 

`install.packages('Rserve',,'http://www.rforge.net/')`

checking whether to compile the server... yes
checking whether to compile the client... no
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for string.h... (cached) yes
checking for memory.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking for sys/types.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/un.h usability... yes
checking sys/un.h presence... yes
checking for sys/un.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking netinet/tcp.h usability... yes
checking netinet/tcp.h presence... yes
checking for netinet/tcp.h... yes
checking for an ANSI C-conforming const... yes
checking whether byte ordering is bigendian... no
checking whether time.h and sys/time.h may both be included... yes
checking for pid_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking return type of signal handlers... void
checking for memset... yes
checking for mkdir... yes
checking for rmdir... yes
checking for select... yes
checking for socket... yes
checking for srandomdev... no
checking for library containing crypt... -lcrypt
checking crypt.h usability... yes
checking crypt.h presence... yes
checking for crypt.h... yes
checking for socklen_t... yes
checking for connect... yes
checking whether to enable IPv6... no
checking for dlopen in -ldl... yes
checking openssl/rsa.h usability... yes
checking openssl/rsa.h presence... yes
checking for openssl/rsa.h... yes
checking for library containing RSA_generate_key... -lcrypto
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for library containing SSL_CTX_load_verify_locations... -lssl
checking whether threads are desired... yes
checking for working threads support... checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
yes
configure: creating ./config.status
config.status: creating src/Makevars
config.status: creating src/client/cxx/Makefile
config.status: creating src/config.h
** libs
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RSserver.c -o RSserver.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Rserv.c -o Rserv.o
Rserv.c: In function ‘performConfig’:
Rserv.c:1035:4: warning: ignoring return value of ‘setgid’, declared with attribute warn_unused_result [-Wunused-result]
    setgid(ruid);
    ^~~~~~~~~~~~
Rserv.c:1036:3: warning: ignoring return value of ‘setuid’, declared with attribute warn_unused_result [-Wunused-result]
   setuid(ruid);
   ^~~~~~~~~~~~
Rserv.c:1039:22: warning: ignoring return value of ‘setgid’, declared with attribute warn_unused_result [-Wunused-result]
   if (requested_gid) setgid(requested_gid);
                      ^~~~~~~~~~~~~~~~~~~~~
Rserv.c:1040:22: warning: ignoring return value of ‘setuid’, declared with attribute warn_unused_result [-Wunused-result]
   if (requested_uid) setuid(requested_uid);
                      ^~~~~~~~~~~~~~~~~~~~~
Rserv.c: In function ‘auth_user’:
Rserv.c:2442:7: warning: ignoring return value of ‘setgid’, declared with attribute warn_unused_result [-Wunused-result]
       setgid(u_gid ? u_gid : default_gid);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Rserv.c:2444:7: warning: ignoring return value of ‘setuid’, declared with attribute warn_unused_result [-Wunused-result]
       setuid(u_uid ? u_uid : default_uid);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c base64.c -o base64.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c http.c -o http.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c ioc.c -o ioc.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c md5.c -o md5.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c oc.c -o oc.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c qap_decode.c -o qap_decode.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c qap_encode.c -o qap_encode.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c rsio.c -o rsio.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c session.c -o session.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c sha1.c -o sha1.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c standalone.c -o standalone.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c tls.c -o tls.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c ulog.c -o ulog.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c utils.c -o utils.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c websockets.c -o websockets.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c winembed.c -o winembed.o
gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o Rserve.so RSserver.o Rserv.o base64.o http.o ioc.o md5.o oc.o qap_decode.o qap_encode.o rsio.o session.o sha1.o standalone.o tls.o ulog.o utils.o websockets.o winembed.o -lssl -lcrypto -ldl -lcrypt -L/usr/lib/R/lib -lR
gcc -std=gnu99 -DSTANDALONE_RSERVE -DDAEMON -I. -Iinclude -I"/usr/share/R/include" -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -pthread    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g   -g -O2 -fdebug-prefix-map=/build/r-base-p1m1mT/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -DRSERVE_PKG -I. -Iinclude   -pthread  -o Rserve standalone.c md5.c session.c qap_decode.c qap_encode.c sha1.c base64.c websockets.c RSserver.c tls.c http.c oc.c rsio.c ulog.c ioc.c utils.c -lssl -lcrypto -ldl -lcrypt    -L"/usr/lib/R/lib" -lR -lssl -lcrypto -ldl -lcrypt  
In file included from standalone.c:6:0:
Rserv.c: In function ‘performConfig’:
Rserv.c:1035:4: warning: ignoring return value of ‘setgid’, declared with attribute warn_unused_result [-Wunused-result]
    setgid(ruid);
    ^~~~~~~~~~~~
Rserv.c:1036:3: warning: ignoring return value of ‘setuid’, declared with attribute warn_unused_result [-Wunused-result]
   setuid(ruid);
   ^~~~~~~~~~~~
Rserv.c:1039:22: warning: ignoring return value of ‘setgid’, declared with attribute warn_unused_result [-Wunused-result]
   if (requested_gid) setgid(requested_gid);
                      ^~~~~~~~~~~~~~~~~~~~~
Rserv.c:1040:22: warning: ignoring return value of ‘setuid’, declared with attribute warn_unused_result [-Wunused-result]
   if (requested_uid) setuid(requested_uid);
                      ^~~~~~~~~~~~~~~~~~~~~
Rserv.c: In function ‘auth_user’:
Rserv.c:2442:7: warning: ignoring return value of ‘setgid’, declared with attribute warn_unused_result [-Wunused-result]
       setgid(u_gid ? u_gid : default_gid);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Rserv.c:2444:7: warning: ignoring return value of ‘setuid’, declared with attribute warn_unused_result [-Wunused-result]
       setuid(u_uid ? u_uid : default_uid);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/ccfJbNEQ.o: In function 'new_tls':
/tmp/Rtmpvy2kcO/R.INSTALL6f352bdf34b9/Rserve/src/tls.c:33: undefined reference to 'SSL_library_init'
/tmp/Rtmpvy2kcO/R.INSTALL6f352bdf34b9/Rserve/src/tls.c:41: undefined reference to 'SSLv23_server_method'
collect2: error: ld returned 1 exit status
Makevars:12: recipe for target 'server' failed
make: *** [server] Error 1
ERROR: compilation failed for package ‘Rserve’

removing ‘/opt/Rlibrary/Rserve’
Warning in install.packages :
  installation of package ‘Rserve’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp0F5lQE/downloaded_packages’

**I have installed openssl with `-fPIC` while it doesn't work**

aaron@aaron:Downloads$ openssl version -a
OpenSSL 1.0.2p  14 Aug 2018
built on: reproducible build, date unspecified
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/local/ssl"

**Thanks for any tips**

**Comment by s-u** [comment]
It works just fine with stock openssl in Ubuntu 18.04:

```
$ openssl version -a
OpenSSL 1.1.0g  2 Nov 2017
built on: reproducible build, date unspecified
platform: debian-amd64
compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/lib/ssl\"" -DENGINESDIR="\"/usr/lib/x86_64-linux-gnu/engines-1.1\"" 
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
```

You're using very old custom OpenSSL, you should remove it.
