### ISSUE TITLE
Rserve TLS not working

### ISSUE THREAD

**Issue by Sharathmk99** [s-u/Rserve#134]
Hi,

I have configured Rseve like below,

workdir /opt/rserve/work
port 6311
interactive no
remote enable
encoding utf8
daemon no
tls.key /opt/rserve/etc/server.key
tls.cert /opt/rserve/etc/server.cert
tls.port 4912
qap disable
switch.qap.tls FALSE

I have generated certificate by below command,
`
openssl req   -newkey rsa:2048   -x509   -nodes   -keyout server.key   -new   -out server.cert   -subj /CN=localhost   -sha256   -days 3650
`
i'm starting my Rserve by below command,
`
R -e 'library(Rserve)' -e 'run.Rserve(config.file = "/opt/rserve/etc/Rserv.conf")'
`
I'm trying to test TLS by below command,
`
RS.connect(host = "localhost", port = 4912, tls = TRUE)
`
I get below error,
TLS handshake failed

Below error i'm getting from server side,
WARNING: discarding buffer because too big (awaiting 7630956811016732950 bytes)

Can you please guide me to fix the issue.

Thank you

**Comment by Sharathmk99** [comment]
@s-u Can you please help

**Comment by s-u** [comment]
Your example works perfectly fine for me in Rserve 1.8-6 on Ubuntu 18.04:

```
> library(RSclient)
> c=RS.connect("localhost", port = 4912, tls = TRUE)
> RS.eval(c,Sys.getpid())
[1] 48246
> Sys.getpid()
[1] 48216
```
Can you give more details? Which platform? Which version? Did you compile both client and server with SSL support etc?

**Comment by Sharathmk99** [comment]
Hi @s-u ,

I'm using inside docker. Please find below details,

FROM r-base:3.6.1
RUN install.r Rserve

How can i compile Rserve server with SSL support?

I think i'm missing something in server setup.

**Comment by Sharathmk99** [comment]
Hi @s-u ,

Its my mistake.
I was installing libssl-dev package after Rserve instllation, so it was not compling with SSL support.

After i installed libssl-dev first and then installed Rserve it works.
Thank you for the hint :)
