### ISSUE TITLE
HTTP API documentation

### ISSUE THREAD

**Issue by jnegara** [s-u/Rserve#137]
I am looking to implement an HTTP client for RServe, however I am unable to find any documentation on RServe's HTTP API.

Can someone either point me towards or create this documentation?

**Comment by 0golovatyi** [comment]
@jnegara As I understand it according to the http://rforge.net/Rserve/news.html (the only documentation I found for the HTTP settings) you will need to provide some HTTP handler implementation written with R. Not sure if I am reading that right...

**Comment by jnegara** [comment]
Thanks!

**Comment by dselivanov** [comment]
> So it seems that I misunderstood the way RServe "supports HTTP" and that there is no stable HTTP API, and that we have to implement our own callback.

That is not correct conclusion - Rserve has stable and performant HTTP API. However:
- HTTP API is not very well documented (but it is simple enough to figure out from Rserve and [FastRWeb](https://github.com/s-u/FastRWeb) source code)
- It is quite low-level, so developer need to handle many things manually (handle errors in user code and provide meaningful HTTP errors, handle missing resources, etc). This is what we address in RestRserve - provide more convenience without sacrificing too much performance.

**Comment by 0golovatyi** [comment]
@dselivanov What is Rserve HTTP API? Looking at the sources I don't see it handles any GET/POST/... requests.

**Comment by dselivanov** [comment]
@0golovatyi  have I you checked links from my message?

> As for documentation - see some hints here
https://github.com/dselivanov/RestRserve/blob/master/CONTRIBUTING.md#rserve-resources


> **http** interface:
    * **request** object format. Rserve passes 4 values (`url`, `query`, `body`, `headers`) to the R code. Parsing logic is described in [FastRWeb::.http.request](https://github.com/s-u/FastRWeb/blob/aaf8847f11903675b1ec7eb9c0e1cc98b92512e5/R/run.R#L58) and [RestRserve:::parse_request](https://github.com/dselivanov/RestRserve/blob/4aecbfb18b8403908c727fa478d161247d591764/R/request.R#L4) functions
    * **response** object from R code defined in [http.c](https://github.com/s-u/Rserve/blob/05ff32d3c4512954a99162d392d0465d432d591e/src/http.c#L353-L372) function inside `Rserve.c`

**Comment by 0golovatyi** [comment]
@dselivanov RestRserve, not Rserve itself. We can't really convert users to RestRserve or any other alternative from Rserve.

**Comment by dselivanov** [comment]
@0golovatyi  have you actually read my answer and information in the links?

**Comment by 0golovatyi** [comment]
Yes, I did. RestRserve, FastRWeb are all good but I was looking for something in Rserve itself.

**Comment by dselivanov** [comment]
Once again

> **http** interface:
    * **request** object format. Rserve passes 4 values (`url`, `query`, `body`, `headers`) to the R code. Parsing logic is described in [FastRWeb::.http.request](https://github.com/s-u/FastRWeb/blob/aaf8847f11903675b1ec7eb9c0e1cc98b92512e5/R/run.R#L58) and [RestRserve:::parse_request](https://github.com/dselivanov/RestRserve/blob/4aecbfb18b8403908c727fa478d161247d591764/R/request.R#L4) functions
    * **response** object from R code defined in [http.c](https://github.com/s-u/Rserve/blob/05ff32d3c4512954a99162d392d0465d432d591e/src/http.c#L353-L372) function inside `Rserve.c`

And this is nothing to do with RestRserve or FastRWeb, this is Rserve http API

**Comment by 0golovatyi** [comment]
I think we are talking about different things. For me "Rserve has HTTP API" means there are HTTP methods I can call with browser/curl/postman/<any http client> for Rserve to evaluate a script, return a list of deployed models, etc. What I see instead is Rserve when receives any HTTP request just calls `.http.request` method which the user will need to write. So yes, there is HTTP support with redirecting request to user code but no HTTP API for Rserve itself.

**Comment by s-u** [comment]
That is the very definition of API - so, yes, there is Rserve HTTP API, very clearly so. I have now copied the documentation to the [HTTP API wiki](https://github.com/s-u/Rserve/wiki/HTTP-API) just to make it more visible.
