### ISSUE TITLE
Bug - Encoding error when starting via jenkins shell execution

### ISSUE THREAD

**Issue by manuelwaltschek** [s-u/Rserve#138]
Hi,

I experience some strange errors. I have setup Rserve on gentoo linux. R version 3.6.1 (2019-07-05) -- "Action of the Toes", Rserve v1.8-6

I'm starting Rserve with the following script:

```#!/usr/bin/Rscript

startRserve = function(){
require(Rserve)
Rserve(args="--no-save --RS-conf /home/rserve/wd/bin/Rserv.conf")
}

startRserve()`
```
My Rserv.conf which is supplied via the startup arguments is configured as follows:

```

workdir /home/rserve/wd
eval setwd('/home/rserve/wd')
workdir.clean enable
interactive disable
source /home/rserve/wd/R-scripts/init/init.R
remote enable
plaintext enable
port 6311
# maxinbuf 262144
encoding utf8
```
Note: I set the encoding to utf8 explicitly. I pass Strings via eval (REngine) to Rserve which serves me ggplot graphics.

I have a Jenkins task configured, which connects to my machine via ssh. It starts and stops Rserve via the startup script and the killall command.
When I connect to my Rserve machine via putty and run them manually, it all works fine, but when I start it via Jenkins script, I get problems displaying axis titles with German umlauts äüöß and so on.

Has anyone had similar problems? Please feel free to help me make a reproducible example, if you need one, as I would need instructions to do so. Thank you in advance,

Manuel

**Comment by s-u** [comment]
I suspect the issue is the locale that you are starting in - I would suggest setting something like `LANG=de_DE.UTF-8`.
