### ISSUE TITLE
keep-alive options

### ISSUE THREAD

**Issue by italopratesi** [s-u/Rserve#139]
Hi,
I use Rserve-1.8.5 in docker containers (linux OS) with mesos as a manager.
To improve performances, I created a pool of r-connections to use machine learning models in R. After a certain period of inactivity, however, when a  connection is used again, it return an error due to the closure of the socket. I'm trying to set keep-alive options between RServe configurations.
I tried to set both keep-alive and keep.alive, but printing the setting at server startup, I find no trace in both cases of the options. Where am I doing wrong ?
Thanks

**Comment by s-u** [comment]
If by "options" you mean the output of `--RS-settings` then those are nowhere close to be exhaustive. Also the `keep.alive` flag is only set, whether keep-alive is supported also depends on the OS, it must have `SO_KEEPALIVE` socket option. Unfortunately, Rserve tends to silently ignore flags that cannot be honored, so if your system doesn't have the socket option, you won't see it. If you have control over the load-balancer then you can just send no-ops to verify the connection and keep it alive regardless of the keep-alive setting.
