### ISSUE TITLE
Request: Enable sending cert chain for SSL handshake.

### ISSUE THREAD

**Issue by jnegara** [s-u/Rserve#140]
I am currently writing a client of a secure Rserve instance that explicitly trusts the root in the certificate chain signing the instance, but none of the intermediate certificates. Currently, Rserve only sends the leaf certificate when performing the SSL handshake. As a result, my client rejects the connection, when really the root CA is within the allowed depth in the chain.

Would anybody be willing to submit a fix/does anybody know a workaround?

**Comment by 0golovatyi** [comment]
I believe the only fix is to add a new optional parameter to use `SSL_CTX_certificate_chain_file()` instead of `SSL_CTX_certificate_file()`.

**Comment by s-u** [comment]
I'm not sure I understand, but isn't that what `tls.ca` is for? See also [TLS/SSL support](https://github.com/s-u/Rserve/wiki/TLS-SSL-support) in the wiki.
