### ISSUE TITLE
Misleading warning message about useplain=yes

### ISSUE THREAD

**Issue by stenevang** [s-u/Rserve#141]
Environment: Windows 10
Rserver version: 1.7-3.1

**Steps to reproduce:**
Start Rserve from command line with R CMD Rserve and a file Rserv.cfg saved in the current working directory (so that the Rserv.cfg file is detected automatically and read)
Let the Rserv.cfg file be empty
View the console output

Warning message in the console says 
```
WARNING: useplain=no, but this Rserve has no crypt support! 
Set useplain=yes or compile with crypt support (if your system supports crypt).
```

**Problem:**
Adding a setting in the configuration file in accordance with the warning message does not remove the warning. Instead, the setting required is
`plaintext enable`

**Proposed solution:**
Change the warning message on line 1604 in Rserv.c to make it helpful.

**Comment by s-u** [comment]
`useplain` is the internal flag that is set by the `plaintext` directive. So it is technically correct, but I can see that it may be confusing for users.
