### ISSUE TITLE
boundary in multipart/* header

### ISSUE THREAD

**Issue by dselivanov** [s-u/Rserve#149]
Hi Simon. We have a report [here](https://github.com/rexyai/RestRserve/issues/137) which seems need to be addressed in `Rserve`. It looks Rserve converts `boundary` value from `multipart/*` header to lower case. But accordingto the HTTP spec, boundary is case-sensitive - [rfc1341](https://www.w3.org/Protocols/rfc1341/4_Content-Type.html) says "For example, multipart boundaries are case-sensitive". And boundary in their example is also case-sensitive (`gc0p4Jq0M2Yt08jU534c0p`)

Here is reproducible example:

```r
.http.request = function(path, query, body, headers) {
  print(attributes(body))
  ""
}
Rserve::run.Rserve(http.port = 8080)
```

```sh
curl -H "Content-Type: multipart/form-data; boundary=AAAAA" -d $'--AAAAA\r\nContent-Disposition: form-data; name="example"\r\n\r\ntest\r\n--AAAAA--\r\n' http://127.0.0.1:8080/hello
```

And the output from R session is 

> $`content-type`
[1] "multipart/form-data; boundary=aaaaa"

**Comment by s-u** [comment]
Ok, I change it, but that was never the intended use of the attribute - for such purposes why not use the actual header. The content-type attribute is not guaranteed to have the full header entry, it is only usable for the type itself. Please the `headers` to extract the full entry.

```r
.http.request = function(path, query, body, headers) { cat(rawToChar(headers)); "" }
```
 Output for above:

```
equest-Method: POST
Host: 127.0.0.1:8080
User-Agent: curl/7.54.0
Accept: */*
Content-Type: multipart/form-data; boundary=AAAAA
Content-Length: 76
```

**Comment by dselivanov** [comment]
Thanks, now we've changed code to get content type from headers directly.

**Comment by s-u** [comment]
Thanks, it is safer that way. I still intend to fix the lower-casing, but for complex uses headers are better (e.g., if the boundary is on the next line it won't be part of the attribute).
