### ISSUE TITLE
Error: long vectors not supported yet: qap_encode.c:36 Fatal error: unable to initialize the JIT

### ISSUE THREAD

**Issue by Forevercoder21** [s-u/Rserve#150]
Hi,
I have followed the thread to fix the issue but had no luck..
https://github.com/s-u/Rserve/issues/102

Can someone take a look this error under this version?

Rserve v1.8-6 ()
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

Thanks!

**Comment by s-u** [comment]
That looks lie a R version mismatch, unrelated to Rserve itself. Please make sure you re-install all packages when you upgrade your R version. Especially, check `.libPaths()` for any libraries you may have forgotten about.

**Comment by Forevercoder21** [comment]
Thanks! 
Still not working.. could you please advise step-by-step to solve the problem?

**Comment by s-u** [comment]
No, since the issue is with your R installation, there is little we can suggest other than deleting R, all packages and re-installing since we cannot know where you have older incompatible binaries installed. As mentioned this has nothing to do wit Rserve, the error comes from R.
