### ISSUE TITLE
Rserve and mongolite

### ISSUE THREAD

**Issue by akross** [s-u/Rserve#153]
Hi,
I'm experiencing a weird behaviour when trying to establish a connection to a remote MongoDB server in Rserve.

My setup is as follows:
- I have an R script that it is loaded as `source` in Rserve config and exposes a function that is responsible to establish the connection to a remote Mongo.
```
init_mongo <- function(db_url = "mongodb+srv://<db_url>/<db_name>") {
     db <- mongo(collection_in, url = db_url)
}
```

- If I try to call this method as it is, the call fails with an `eval failed` error.
Eg.
```
RConnection c = new RConnection();
REXP eval = c.parseAndEval("try(init_mongo(), silent=TRUE)");
```

- the only way I found it would work, is to establish the connection first outside of the function and then call the function. 
Eg.
```
mongo(collection_in, url = "mongodb+srv://<db_url>/<db_name>")

init_mongo <- function(db_url = "mongodb+srv://<db_url>/<db_name>") {
     db <- mongo(collection_in, url = db_url)
}
```

So the first call to mongo() would be done when sourcing the file, and the second one when the function is actually called through Rserve.
If I point to a local mongo as db_url = "mongodb://localhost:27017/<db_name", everything works as expected without the external call.

Is there something I'm missing here?

Thanks,
Marco

**Comment by s-u** [comment]
Where is `collection_in` defined? I don't see how the first one can work since you'd have to define in the lexical scope of the function (remember R is lexically scoped, not dynamically scoped). Maybe that's a red herring, but you didn't provide the actual error.
