### ISSUE TITLE
Rserve.eval and custom error conditions

### ISSUE THREAD

**Issue by dselivanov** [s-u/Rserve#154]
Hi Simon,

I'm trying to figure out how to use `Rserve.eval` to safely evaluate expression and get stack trace in case of fail. I face couple of challenges:

- It doesn't seem possible to get additional fields supplied by condition object and it's class, only error message.  Would it be possible to retain full condition object with the class attribute, not only message?
- I can't figure out how to mute error message produced by `Rserve.eval` (such as `"Error: this is an error with condition"` in example below). I can sink all the stderr stream to `/dev/null` before  `Rserve.eval` call, but then all the messages produced by evaluated expression will also go to `/dev/null`...

Consider following example:

```r
error_with_condition = function(object = NULL) {
  cond = errorCondition("this is an error with condition", 
                        object = object, 
                        class = "CustomError")
  stop(cond)
}
caught_err = tryCatch(error_with_condition(1), error = identity)
str(caught_err)
#List of 3
# $ message     : chr "this is an error with condition"
# $ call        : NULL
# $ custom_field: chr "hello"
# - attr(*, "class")= chr [1:3] "CustomError" "error" "condition"

caught_rserve_eval = Rserve::Rserve.eval(quote(error_with_condition("hello")), last.value = TRUE)
#  Error: this is an error with condition

str(caught_rserve_eval)
#List of 4
#$ error     : chr "Error: this is an error with condition\n"
# $ traceback :Dotted pair list of 2
#  ..$ : chr "stop(cond)"
#  ..$ : chr "error_with_condition(\"hello\")"
# $ expression: int NA
# $ context   : NULL
# - attr(*, "class")= chr "Rserve-eval-error"
```

**Comment by s-u** [comment]
I don't think R actually allows any of the above. The problem is that the C-level interface is very limited when it comes to error handling and it doesn't support condition objects. The error comes directly from `R_curErrorBuf()` so Rserve is just a pass-through from R. I'll see if I can dig out more or if we could add more support in R.

**Comment by dselivanov** [comment]
@s-u do you think there is a chance to get such improvement in R 4.1? Should I create a ticket on R-bugzilla?

**Comment by s-u** [comment]
Ok, I have been digging through the whole mess of condition handling in R and I think I have at least a work-around for catching the conditions. Essentially it involves installing a calling handler for the `"error"` condition which stashes the condition, but then continues to the default handler to trigger the error so we get the traceback.

**Comment by s-u** [comment]
```r
error_with_condition = function(object = NULL) {
  cond = errorCondition("this is an error with condition", 
                        object = object, 
                        class = "CustomError")
  stop(cond)
}

caught_rserve_eval = Rserve::Rserve.eval(quote(error_with_condition("hello")), last.value = TRUE)
# Error: this is an error with condition

str(caught_rserve_eval)
# Class 'Rserve-eval-error'  hidden list of 5
#  $ error     : chr "Error: this is an error with condition\n"
#  $ traceback :Dotted pair list of 2
#   ..$ : chr "stop(cond)"
#   ..$ : chr "error_with_condition(\"hello\")"
#  $ expression: int NA
#  $ context   : NULL
#  $ condition :List of 3
#   ..$ message: chr "this is an error with condition"
#   ..$ call   : NULL
#   ..$ object : chr "hello"
#   ..- attr(*, "class")= chr [1:3] "CustomError" "error" "condition"
```

**Comment by s-u** [comment]
The mechanism is fairly generic, so it would be possible to allow injection of arbitrary handlers, so I am reserving the right to change the API for the `handler` argument - it could be a list just like in `tryCatch`, but for now only one handler is added so if that sounds like a good idea that may be useful, please feel free to file a feature request.

**Comment by s-u** [comment]
Never mind the last comment - I have now changed the API in 57d1c80 such that `handlers` is a named list of handlers, so arbitrary calling handlers can be registered with the default being `handlers = list(error = .save.condition)` which saves the condition for retrieval upon return from `Rserve.eval`.
