### ISSUE TITLE
run.Rserve() does not process source and eval configuration directives

### ISSUE THREAD

**Issue by okhoma** [s-u/Rserve#157]
It looks like `run.Rserve()` does not process source and eval directives in configuration file. This is only done in `main()` function in `standalone.c` (https://github.com/s-u/Rserve/blob/484f5fedbaa906c9836464eff15dc896b11080f3/src/standalone.c#L227).

It was a surprise, given that `run.Rserve()` does process configuration file.  Was it maybe intentional? If yes, then, perhaps documentation should be updated to highlight that.

Thanks

**Comment by s-u** [comment]
Correct, those are irrelevant when you start from a session since you can use `source()` and `eval()` there already. They are the replacement of a session in the stand-alone mode where you have no other choice.
