### ISSUE TITLE
Does rserve support R 4.0?

### ISSUE THREAD

**Issue by cesarsalgado** [s-u/Rserve#158]
Since there were some breaking changes introduced in R 4.0 I am wondering if rserve officially supports it.

**Comment by dselivanov** [comment]
What kind of breaking changes which affect Rserve do you have in mind? I don't have any problems running it with R 4.0.*

**Comment by cesarsalgado** [comment]
This one came to my mind:
```
R now uses a stringsAsFactors = FALSE default, and hence by
      default no longer converts strings to factors in calls to
      data.frame() and read.table().

      A large number of packages relied on the previous behaviour and
      so have needed/will need updating.
```
from https://stat.ethz.ch/pipermail/r-announce/2020/000653.html

**Comment by s-u** [comment]
@cesarsalgado Rserve doesn't care abut that change whatever - it is a user-facing change.
