### ISSUE TITLE
Tildes in config file not supported

### ISSUE THREAD

**Issue by ericedelman-gh** [s-u/Rserve#159]
It seems that when specifying the path to key and certificate files in Rserv.conf using a tilde to refer to the home directory, this does not load the specified files.

**Comment by s-u** [comment]
Please note that `~` is a shell expansion feature, it is not valid in filenames, i.e. "~/foo" is specifying a relative path to "~" directory and file "foo" inside it.

In the config file Rserve supports expansion of environment variables using `${FOO}` notation where `FOO` is the env var name. This is more general as it doesn't treat configuration values that happen to be paths in any special way and you can still use `${HOME}/foo` to achieve what you intended.

**Comment by ericedelman-gh** [comment]
That makes sense, thanks.
