### ISSUE TITLE
Errors in loading key and certificate files fail silently

### ISSUE THREAD

**Issue by ericedelman-gh** [s-u/Rserve#160]
When the key and certificate files specified in Rserv.conf fail to load, this does not produce any messages, only resulting in a TLS handshake failure when later trying to connect to the server.

**Comment by s-u** [comment]
The proxy now handles that since 7eb30c2 so likely we should do the same for Rserve that is used without the proxy.

**Comment by ericedelman-gh** [comment]
Those changes to the proxy look perfect, it would be great to have the same functionality for the main Rserve. Thanks so much.

**Comment by s-u** [comment]
This should now be addressed by efff0e3
For compatibility is just a warning. Part of the issue is that TLS initialization is de-centralized in Rserve, so the validity is not actually checked until a connection is initiated.
