### ISSUE TITLE
Fails to compile on recent OS X clang/xcode

### ISSUE THREAD

**Issue by dselivanov** [s-u/Rserve#162]
It seems apple now raising error on "-implicit-function-declaration" warning. 

So I'm getting following errors:
> Rserv.c:2514:45: error: implicit declaration of function 'ERR_error_string' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                Rf_warning("cannot allocate RSA key: %s", ERR_error_string(ERR_get_error(), NULL));
                                                          ^
Rserv.c:2514:62: error: implicit declaration of function 'ERR_get_error' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                Rf_warning("cannot allocate RSA key: %s", ERR_error_string(ERR_get_error(), NULL));
                                                                           ^
Rserv.c:2521:47: error: implicit declaration of function 'ERR_error_string' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        Rf_warning("cannot allocate exponent: %s", ERR_error_string(ERR_get_error(), NULL));
                                                                   ^
Rserv.c:2521:64: error: implicit declaration of function 'ERR_get_error' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        Rf_warning("cannot allocate exponent: %s", ERR_error_string(ERR_get_error(), NULL));
                                                                                    ^
Rserv.c:2528:42: error: implicit declaration of function 'ERR_error_string' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        Rf_warning("cannot generate key: %s", ERR_error_string(ERR_get_error(), NULL));
                                                              ^
Rserv.c:2528:59: error: implicit declaration of function 'ERR_get_error' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        Rf_warning("cannot generate key: %s", ERR_error_string(ERR_get_error(), NULL));

Adding `-Wno-error=implicit-function-declaration` to `CFLAGS` in `~/.R/Makevars` helps, but would be great to if Rserve can address internally as many users won't be able to fix it themselves.

```
xcode-select --version
```
> xcode-select version 2373.
```
clang --version
```
> Apple clang version 12.0.0 (clang-1200.0.32.21)
> Target: x86_64-apple-darwin19.6.0

**Comment by Bio7** [comment]
I added the following declarations to Rserv.c

https://github.com/renepickhardt/lightning/commit/b8bf887515d7472dd17737b29828c0d5287360da

Worked for me with 1.8-7 on Big Sur

**Comment by Bio7** [comment]
Just for completeness (and to safe you some time) I unpack the Rserve archive in a directory. In the directory I execute the following command to built and install Rserve on MacOSX:

`sudo PKG_CPPFLAGS=-DCOOPERATIVE R CMD INSTALL --build Rserve`

I hope it helps!

**Comment by s-u** [comment]
Should be fixed by c9f7883
