### ISSUE TITLE
RServe -   Forecast and Mvoutlier  Packages works with  SSL disabled  but fails with SSL enabled.

### ISSUE THREAD

**Issue by rajanandam** [s-u/Rserve#167]
We currently have issue with ForeCast Package not working on RServe with SSL enabled connection.  When we disable SSL the  same scripts works . 

Below scripts not working when SSL enabled for RServe  frequency=12  but works for frequency 1 to 4
==========================================================
SCRIPT_REAL("library(forecast); 
time <- ts(.arg1,start=c(2018,1), frequency=12);
fcst <- forecast(time, h=.arg2[1]);
n<-length(.arg1);
append(.arg1[(.arg2[1]+1):n],fcst$mean, after = n-.arg2[1])",
SUM([Dollars]), [Period M])

Working when SSL enabled or disabled - as frequency = 1 and Period is Year.
==========================================================
SCRIPT_REAL("library(forecast);
time <- ts(.arg1,start=c(2016,1), frequency=1);
fcst <- forecast(time, h=.arg2[1]);
n<-length(.arg1);
append(.arg1[(.arg2[1]+1):n],fcst$mean, after = n-.arg2[1])",
SUM([Dollars]), [Period Y])
============================

**Comment by s-u** [comment]
Closing because incomplete.
