### ISSUE TITLE
RServe SSL connection - buffer size issue

### ISSUE THREAD

**Issue by DavidDurston** [s-u/Rserve#170]
Hello, starting a fresh topic instead of reviving a closed one... I've been trying to get Tableau to connect to Rserve. At first very successfully via HTTP, but Tableau Online requires HTTPS. So I have a domain for the Rserve server, as well as an SSL certificate issued by Let's Encrypt. However attempting to connect over HTTPS continues to fail. I've scoured the web all day, tried different versions of Rserve, tried different sizes of the server (EC2 instance) for good measure. I cannot get past this. Below are relevant snippets:

Rserv.conf
```
remote enable
port 6311
auth required
pwdfile /etc/Ruser.txt
plaintext enable
maxinbuf 4194304
tls.key /etc/letsencrypt/live/{website-url}/privkey.pem
tls.cert /etc/letsencrypt/live/{website-url}/cert.pem
```
Not that above, the key and cert files... I cannot normally 'cd' into that live folder without sudo so I'm not totally sure it's able to read them, but it's not showing me any error either.

Logs from a successful connection (HTTP):
```
INFO: accepted connection for server 0x55df7efa4160, calling connected
connection accepted.
sending ID string.

header read result: 16
DUMP [16]: 01 00 00 00 10 00 00 00 00 00 00 00 00 00 00 00  |................
loading buffer (awaiting 16 bytes)
parsing parameters (buf=0x55df7f3f80f0, len=16)
DUMP [16]: 04 0c 00 00 72 75 73 65 72 0a 72 70 61 73 73 00  |....ruser.rpass.
PAR[0]: 00000010 (PAR_LEN=12, PAR_TYPE=4, large=no, c=0x55df7f3f80f0, ptr=0x55df7f3f80f4)
CMD=00000001, pars=1
Authentication attempt (login='ruser', pwd='rpass', pwdfile='/etc/Ruser.txt')
Found login 'ruser', checking password.
 - stored pwd = 'rpass', md5='74b91298945992e3a5760e7885686e4a', sha1='a1a80c014d2c548081fce70de68d6fb078fb7d2b'
 - plain password matches.
OUT.sendRespData
HEAD DUMP [16]: 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00  |................
(no body)
Connection closed by peer.
done.
```

And logs from a failed connection (HTTPS):
```
INFO: accepted connection for server 0x55df7efa4160, calling connected
connection accepted.
sending ID string.

header read result: 16
DUMP [16]: 16 03 01 01 20 01 00 01 1c 03 03 2a c1 eb 37 4c  |.... ......*..7L
WARNING: discarding buffer because too big (awaiting 5492117484779602208 bytes)
Connection closed by peer.
done.
```

Would greatly appreciate any support. I'm at my wit's end trying to figure this out.

**Comment by s-u** [comment]
Sorry, I fear you'll have contact Tableau support since the configuration (HTTP/HTTPS) you talk about has nothing to do with Rserve. In your Rserve config you are not enabling HTTP nor HTTPS and Rserve doesn't use either to serve R scripts so you must be confusing some Tableau part with Rserve. I don't have the slightest idea what the Tableau client is doing or what configuration it requires so you need to consult Tableau documentation.

FWIW your config sets the TLS keys, but doesn't actually enable TLS. Depending which services you want to encrypt, you'd need one of: `tls.qap.port` for QAP1 direct TLS, `switch.qap.tls` for upgrade in QAP1 from plain to TLS (then you still use `port` and upgrade),  `websockets.tls.port` for WebSockets TLS server or `https.port` for HTTPS (web-content only, not QAP1 so not likely useful to you).

**Comment by s-u** [comment]
[As an aside - mostly to anyone from Tableau if they come here - the above approach is strongly discouraged, ever since Rserve introduced OCAP model it is far more secure and thus anyone seriously considering a product on top of Rserve should be using it - see (RCloud)[https://github.com/att/rcloud] for an example - since using Rserve without OCAP mode allows arbitrary code execution by design. Also OCAP allows much more secure and flexible authentication.]

**Comment by DavidDurston** [comment]
Thank you for the speedy response. I figured as much RE what Tableau is doing under the hood. Outside of that, is there any command I can run from the machine itself to test the encrypted connection to Rserve, to verify that my config file and SSL cert/key are even setup properly? I'd like to at least verify that part before assuming it's entirely an issue with Tableau.

Appreciate your help - yesterday was my first day ever hearing about Rserve so this is all very fresh to me :)

**Comment by DavidDurston** [comment]
Hi Simon,

I finally had time to revisit this and have more info. I have a new/official SSL cert, and I've now tried connecting using RSclient and can confirm I'm getting the same issue, so, as thought, it may not be a Tableau issue after all.

My Rserv.conf:
```
remote enable
port 6311
auth required
pwdfile /etc/Ruser.txt
plaintext disable
encoding utf8
tls.key /home/ubuntu/sonyssl/mykey.key
tls.cert /home/ubuntu/sonyssl/mycert.crt
tls.port 4912
qap disable
```

The commands I'm running:
```
> library(Rserve)
> Rserve(args="--RS-conf /etc/Rserv.conf --no-save")
Starting Rserve:
 /usr/lib/R/bin/R CMD /home/ubuntu/R/x86_64-pc-linux-gnu-library/3.6/Rserve/libs//Rserve --RS-conf /etc/Rserv.conf --no-save 

[...]

Rserv started in daemon mode.
> library(RSclient)
> c=RS.connect("localhost", port = 4912, tls = TRUE)
WARNING: discarding buffer because too big (awaiting 5954770885163352342 bytes)
Error in RS.connect("localhost", port = 4912, tls = TRUE) : 
  TLS handshake failed (SSL_error=1; error:1408F10B:SSL routines:ssl3_get_record:wrong version number)
```

You mentioned some other parameters that I might need to set in the .conf file in one of your last responses (tls.qap.port, etc). Could you please elaborate, or tell me if I'm still not actually enabling TLS? I'm not seeing those keys you mentioned in the documentation for Rserve.

Really appreciate the help. Thank you.

**Comment by s-u** [comment]
Are you sure you have the correct TSL key/cert? Unfortunately the TLS engine won't complain if they are invalid and it will just disable TLS. The above works just fine for me:

```
$ R CMD /Library/Frameworks/R.framework/Versions/4.1/Resources/library/Rserve/libs//Rserve.dbg --RS-conf Rserv.conf --silent
Rserve 1.8-8 () (C)Copyright 2002-2013 Simon Urbanek
$Id$

Loading config file /etc/Rserv.conf
Failed to find config file /etc/Rserv.conf
Loading config file Rserv.conf
conf> command="remote", parameter="enable"
conf> command="auth", parameter="required"
conf> command="pwdfile", parameter="Ruser.txt"
conf> command="plaintext", parameter="disable"
conf> command="encoding", parameter="utf8"
conf> command="tls.key", parameter="example.key"
conf> command="tls.cert", parameter="example.crt"
conf> command="tls.port", parameter="4912"
conf> command="qap", parameter="disable"
Loaded config file Rserv.conf
 - create_server(port = 4912, socket = <NULL>, mode = 0, flags = 0x800)
INFO: adding server 0x7fadc54f7e30 (total 1 servers)
Rserve: Ok, ready to answer queries.
INFO: accepted connection for server 0x7fadc54f7e30, calling connected
connection accepted.
sending ID string.
Connection closed by peer.
done.

## client (I'm using verify=FALSE since it's just localhost)
> c=RSclient::RS.connect("localhost", port = 4912, tls = TRUE, verify=FALSE)
> RSclient::RS.close(c)

## FWIW without verify you get correctly
> c=RSclient::RS.connect("localhost", port = 4912, tls = TRUE)
Error in RSclient::RS.connect("localhost", port = 4912, tls = TRUE) : 
  TLS handshake failed (SSL_error=1; error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed)
```

**Comment by DavidDurston** [comment]
Hi Simon, sorry for the delay - was out of town.

Thank you for the continued support! Using the above commands, I do have matching outputs as well for my key and cert. However running the "forward" command results in: ```ERROR: unable to initialize SSL - you may be missing SSL support.``` I'm honestly not sure the SSL/Apache setup even matters in this case, but I'm sure it must be setup correctly since the browser picks it up as the page being secured/verified-by.

I noticed this other Issue thread here mentioning a "libssl-dev" package. I do seem to have it, I believe. If related, do I need to somehow link that to the Rserve package?
```
$ apt list --installed libssl*
Listing... Done
libssl-dev/focal-security,now 1.1.1f-1ubuntu2.3 amd64 [installed,upgradable to: 1.1.1f-1ubuntu2.4]
libssl1.1/focal-security,now 1.1.1f-1ubuntu2.3 amd64 [installed,upgradable to: 1.1.1f-1ubuntu2.4]
```

To answer your other question, I installed Rserve via ```sudo apt install r-cran-rserve ``` and my version of that seems to be:
```
$ apt list --installed r-cran-rserve
Listing... Done
r-cran-rserve/focal,now 1.7-3.1-2 amd64 [installed]
```
Though when starting it up I see the same thing you do:
```Rserve 1.8-8 () (C)Copyright 2002-2013 Simon Urbanek```

**Comment by s-u** [comment]
@DavidDurston When you install Rserve, make sure is detects SSL support, so when you run `install.packages("Rserve",,"https://rforge.net")` check the output - you should see something like

```
checking openssl/rsa.h usability... yes
checking openssl/rsa.h presence... yes
checking for openssl/rsa.h... yes
checking for library containing RSA_generate_key... -lcrypto
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for library containing SSL_CTX_load_verify_locations... -lssl
```

**Comment by DavidDurston** [comment]
I ran that install method and did see all of those lines exactly as you shared them.

Perhaps my install method differing was an issue, because now when I run RS.connect(), instead of seeing
```TLS handshake failed (SSL_error=1; error:1408F10B:SSL routines:ssl3_get_record:wrong version number)```
I now see
```TLS handshake failed (SSL_error=1; error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed)```

Running those openssl commands still gets me matching outputs, though. I know longer see the "buffer too big" issue. I know the certs are successfully being used for other things, so they are working.

**Comment by s-u** [comment]
@DavidDurston ok, good, it means you have TLS support now. You can use `RS.connect(..., verify=FALSE)` if you have a self-signed certificate. If you want full chain of trust and you have any intermediate certificates (very common these days), make sure you also set `tls.ca` with the CA certificate chain.

**Comment by DavidDurston** [comment]
@s-u I see, that may be what I'm missing in the config file, then. Will look into that and report back. I do get it working fine when testing with verify=FALSE as you did a few messages back... but again, trying to connect with an external client so that won't work.

**Comment by DavidDurston** [comment]
@s-u I've added the following line to my config:
```tls.ca /home/ubuntu/sonyssl/DigiCertCA.crt```

And am now seeing a slight addition to the error when trying RS.connect()
```
> c=RS.connect("localhost", port = 4912, tls = TRUE)
Error in RS.connect("localhost", port = 4912, tls = TRUE) : 
  TLS handshake failed (SSL_error=1; error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed)
> Error: ignoring SIGPIPE signal
*** stack smashing detected ***: terminated
```

However when I try to connect from the client (Tableau) the error is allegedly one of authentication:
```
Rserve: Ok, ready to answer queries.
INFO: accepted connection for server 0x560cb7abf1b0, calling connected
connection accepted.
sending ID string.

header read result: 16
DUMP [16]: 01 00 00 00 10 00 00 00 00 00 00 00 00 00 00 00  |................
loading buffer (awaiting 16 bytes)
parsing parameters (buf=0x560cb9199980, len=16)
DUMP [16]: 04 0c 00 00 72 75 73 65 72 0a 72 70 61 73 73 00  |....ruser.rpass.
PAR[0]: 00000010 (PAR_LEN=12, PAR_TYPE=4, large=no, c=0x560cb9199980, ptr=0x560cb9199984)
CMD=00000001, pars=1
Authentication attempt (login='ruser', pwd='rpass', pwdfile='/etc/Ruser.txt')
Found login 'ruser', checking password.
 - stored pwd = 'rpass', md5='74b91298945992e3a5760e7885686e4a', sha1='a1a80c014d2c548081fce70de68d6fb078fb7d2b'
 - checking crypted '8cM3t82neJ80c' vs 'rpass'
OUT.sendRespData
HEAD DUMP [16]: 02 00 01 41 00 00 00 00 00 00 00 00 00 00 00 00  |...A............
(no body)
```

**Comment by s-u** [comment]
@DavidDurston almost there, it seems that Tableau is passing plain-text passwords, so it may require `plaintext enable`.

FWIW I have now added a Wiki page [TLS/SSL support](https://github.com/s-u/Rserve/wiki/TLS-SSL-support) in an attempt to clarify things on TLS front.

**Comment by DavidDurston** [comment]
It's working at long last! Thank you, very much. Perused the new documentation as well, I'm sure it'll be helpful to others down the road.

**Comment by rkirkish** [comment]
I ran through the steps above:
```
$ openssl rsa -modulus -noout -in ~/keys/server.key | openssl md5
(stdin)= 50999c2bb0291cbc7762839f12ee4c92
$ openssl x509 -modulus -noout -in ~/keys/server.crt | openssl md5
(stdin)= 50999c2bb0291cbc7762839f12ee4c92
```
I receive matching hashes. I created the `self-signed` certs.

Note, the certs were created with (per Rserve [NEWS](https://www.rforge.net/Rserve/news.html):
```
openssl genrsa -out server.key 2048
openssl req -new -key server.key -out server.csr
openssl x509 -req -days 365 -in server.csr \
                  -signkey server.key -out server.crt
```

However, this command hangs (with no response) and I'm not sure how to interpret that:
```
/usr/local/lib/R/site-library/Rserve/libs/forward -k ~/keys/server.key -c ~/keys/server.crt
```

Note:
```
/usr/local/lib/R/site-library/Rserve/libs/Rserve --version

Rserve v1.8-10 ()
R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

**What I'm trying to accomplish:**
I'm trying to establish connection to Tableau server (Tableau Server Version: 2021.1.4 (20211.21.0712.0907) 64-bit Windows) using analytics extension with require SSL option flagged.

Running Rserve on AWS EC2 via:
```
R CMD Rserve.dbg
```

With config:
```
remote enable
encoding utf8
plaintext enable
auth required
verify FALSE
pwdfile /etc/rcreds.prod
tls.key /root/keys/server.key
tls.cert /root/keys/server.crt
qap.tls.port 4912
switch.qap.tls FALSE
maxinbuf 4194304
```

Leads to:
``` - create_server(port = 6311, socket = <NULL>, mode = 0, flags = 0x0)
INFO: adding server 0x55596180f130 (total 1 servers)
 - create_server(port = 4912, socket = <NULL>, mode = 0, flags = 0x800)
 -```


If it helps, here's the message from Rserve debug when Tableau points to port: `6311`:
```
INFO: accepted connection for server 0x55e79709f130, calling connected
ULOG:  INFO: new child process 73 (parent 65)
connection accepted.
sending ID string.

header read result: 16
DUMP [16]: 16 03 01 01 1a 01 00 01 16 03 03 f4 32 cb 56 15  |............2.V.
ULOG:  QAP1: CMD 0x01010316, length 1537639738419183898, msg.id 0x0
WARNING: discarding buffer because too big (awaiting 1537639738419183898 bytes)
malformed packet (n=-1). closing socket to prevent garbage.
ULOG:  INFO: closed connection
```
Here's the Tableau Server message:
```
Failed to validate the remote server's SSL certificate. Verify that the certificate is valid, and signed by a trusted authority
```

Pointing Tableau to `4912` , however, leads to no communication between servers.

Any help is much appreciated.

**Comment by s-u** [comment]
@rkirkish I'm not sure what you intend with the above so I'll just comment on individual parts:

## Proxy
`forward` is a WebSockets <-> QAP proxy which is used in situations where you want to use HTTP+WS and isolate it from compute processes. It is typically used with [rserve-js](https://github.com/att/rserve-js) such as enterprise deployments of [RCloud](https://github.com/att/rcloud). It doesn't "hang" - the service is listening on the 8088 port (default) for incoming connections. However, to my best knowledge based on the other posts above Tableau uses QAP directly (not in a WebSocket tunnel) so you don't want to use the proxy.

## QAP plain
In your setup above you have bound 6311 to plain QAP. Again, from above I'd say that doesn't help you with Tableau so you probably want `qap disable`(see the workin config above) or can ignore as it's simply now used here (unless Tableau supports TLS upgrade which I don't know - but given that you disabled it with `switch.qap.tls` I assume it doesn't).

## QAP TLS
The last one sounds most promising - just there is no`verify` configuration option - did you mean `tls.client none`? That one makes sure that client certificate is not required from Tableau. You said "leads to no communication" - what do you mean exactly and did you perhaps fail to forward the docker port?

**Comment by s-u** [comment]
PS: I like the idea of providing a Docker container - this seems to crop up enough that having a canonical on DockerHub would be useful. I'm happy to help but I'd need one of you guys to test since I don't have Tableau.

PPS: I didn't know about [pyRserve](https://github.com/ralhei/pyRserve), cool! @ralhei

**Comment by rkirkish** [comment]
@s-u I'd be more than happy to help test!

Thanks for the explanation above. I may be crossing topics in my thrash towards getting my Tableau server integrated with Rserve with SSL enabled. Looks like QAP TLS is what I'm trying to enable.

I've updated my config to the following:
```
conf> command="remote", parameter="enable"
conf> command="encoding", parameter="utf8"
conf> command="plaintext", parameter="enable"
conf> command="auth", parameter="required"
conf> command="tls.client", parameter="none"
conf> command="pwdfile", parameter="/etc/rcreds.prod"
conf> command="tls.key", parameter="/root/keys/server.key"
conf> command="tls.cert", parameter="/root/keys/server.crt"
conf> command="qap.tls.port", parameter="4912"
conf> command="switch.qap.tls", parameter="FALSE"
conf> command="maxinbuf", parameter="4194304"
``` 
This creates two servers:
```
 - create_server(port = 6311, socket = <NULL>, mode = 0, flags = 0x0)
INFO: adding server 0x565004892130 (total 1 servers)
 - create_server(port = 4912, socket = <NULL>, mode = 0, flags = 0x800)
INFO: adding server 0x565005f204c0 (total 2 servers)
```

I'll remove Tableau as the client since the issue may be with Tableau and my understanding of how it's analytics extension works and replace with local R:
`R version 4.1.2 (2021-11-01) -- "Bird Hippie"`

Given that setup: 
I'm now operating with the assumption that `successful communication to Rserve from a client will be encrypted over the internet`.

I run R:
```
> library("RSclient")
> c <- RS.connect("ec2-35-85-247-207.us-west-2.compute.amazonaws.com")
> RS.login(c, "<user>", "<password>", authkey=RS.authkey(c))
[1] TRUE
> x <- rnorm(1e2)
> RS.eval(c, as.call(list(quote(sum),x)), lazy=FALSE)
[1] -11.91975
```

Rserve running in debug mode within docker on EC2 logs:
```
header read result: 16
DUMP [16]: f5 00 00 00 5a 03 00 00 00 00 00 00 00 00 00 00  |....Z...........
ULOG:  QAP1: CMD 0x000000f5, length 858, msg.id 0x0
loading (raw) buffer (awaiting 858 bytes)
CMD=000000f5, pars=0
ULOG:  QAP1: sending response 0x00010001, length 39, msg.id 0x0
OUT.sendRespData
HEAD DUMP [16]: 01 00 01 00 27 00 00 00 00 00 00 00 00 00 00 00  |....'...........
BODY DUMP [39]: 58 0a 00 00 00 03 00 04 01 02 00 03 05 00 00 00 00 05 55 54 46 2d 38 00 00 00 0e 00 00 00 01 c0 27 d6 ea 1b 67 2a e6  |X.................UTF-8.........'...g*.
```

So the client and server are communicating. However, I don't know why communication would be encrypted if it is at all. The client (R) didn't pass `server.crt`.

I also don't know what port is handling the requests? Does `6311` proxy to `4912` in this scenario?

Note Docker for running R-base:
```
FROM r-base

RUN apt-get update \
        && apt-get install -y \
               libssl-dev \
               openssl \
               make \
               gcc \
               g++ \
               bash-completion \
               automake

RUN Rscript -e 'install.packages("RSclient")'

ENTRYPOINT R
```

**Comment by s-u** [comment]
@rkirkish You are starting two entirely different severs: one on port 6311 using QAP and one on port 4912 using QAP in TLS tunnel. They have in a sense nothing to do with each other except that they are served by the same process.

Then your test uses the default port 6311 with QAP:

```r
RS.connect(host = NULL, port = 6311L, tls = FALSE, verify = TRUE,
           proxy.target = NULL, proxy.wait = TRUE, chain, key, ca)
```

so the QAP server (without TLS). Since you use `RS.authkey`+`RS.login` that is the secure RSA-encrypted authentication so the authentication itself is encrypted, but nothing else (see [Security](https://github.com/s-u/Rserve/wiki/Security) for details on the different authentication methods).

At the same time you started another server on port 4912 which uses QAP tunnel over TLS (see [TLS](https://github.com/s-u/Rserve/wiki/TLS-SSL-support) for details on that). You can test that with `tls=TRUE`:

```r
> c=RS.connect("myhost", port=4912, tls=TRUE, verify=FALSE)
> RS.login(c, "user", "password", authkey=RS.authkey(c))
[1] TRUE
> RS.eval.qap(c, quote(sum(rnorm(1e4))))
[1] 1.011597
```

on the server you will see:

```
 - create_server(port = 4912, socket = <NULL>, mode = 0, flags = 0x800)
INFO: adding server 0x7f81bafebe00 (total 1 servers)
Rserve: Ok, ready to answer queries.
ULOG:  INFO: Rserve server loop started
INFO: accepted connection for server 0x7f81bafebe00, calling connected
ULOG:  INFO: new child process 53160 (parent 53151)
connection accepted.
INFO: peer nas NO cert
sending ID string.

header read result: 16
DUMP [16]: 06 00 00 00 10 00 00 00 00 00 00 00 00 00 00 00  |................
ULOG:  QAP1: CMD 0x00000006, length 16, msg.id 0x0
loading buffer (awaiting 16 bytes)
 [2] rn = 16 (i = 0)
[...]
```

Really the only difference in the output is the line

    INFO: peer nas NO cert

which tells you that it is a TLS connection, i.e., the entire communication is encrypted.

This is the config I was using above and from what I have seen it should be sufficient to start the one server you need for Tableau (but can't test myself):

```
remote enable
encoding utf8
plaintext enable
auth required
tls.client none
pwdfile ${PWD}/passwd
tls.key server.key
tls.cert server.crt
qap disable
qap.tls.port 4912
```

**Comment by rkirkish** [comment]
Thanks @s-u I'm testing this week.
