### ISSUE TITLE
Fatal error: unable to open the base package in Windows 10 with R-4.1.0

### ISSUE THREAD

**Issue by kimmolinna** [s-u/Rserve#171]
I will get `Fatal error: unable to open the base package` when I try to start `Rserve.exe` in command prompt after I have copied `Rserve.exe` and `Rserve.dll `to the same folder with `R.dll(bin/x64)`. I don't have any problem to start Rserve in `R` with commands
```
> library(Rserve)
> Rserve()
Starting Rserve...
 "C:\Users\kimmo\R-41~1.0\library\Rserve\libs\x64\Rserve.exe" 
> 
``` 
And in Linux everything is working fine with 4.1.0 in Kubuntu 21.04.

**Comment by s-u** [comment]
You may have to use `R CMD Rserve` or else all the important variables like `R_HOME` are not set. If you run it from R then they are set already by R itself. Older versions of Rserve detected those settings from registry, but given the severe limitations of Windows it doesn't really make sense to run Rserve there and thus the support is very minimal.

**Comment by kimmolinna** [comment]
R CMD Rserve is working nicely.
