### ISSUE TITLE
TLS handshake failed when using Rserve with RSclien in local RStudio

### ISSUE THREAD

**Issue by cljambo** [s-u/Rserve#172]
Hi,

I am running Rserve 1.8.8 on a separate SLES 15 SP1 (in Azure cloud I think) and R 3.5.0. On my local computer I have RStudio with R 3.6.3 and RSclient 0.7.3 installed.

I get the error message "TLS handshake failed" when trying to make an authenticated connection with Rserve:
![image](https://user-images.githubusercontent.com/66958155/120607266-4fca0700-c450-11eb-84a9-9bd1fce76e4e.png)

Rserv.conf looks as follows:
![image](https://user-images.githubusercontent.com/66958155/120607318-5d7f8c80-c450-11eb-85cf-7a165150eb64.png)

Rserve was started with ![image](https://user-images.githubusercontent.com/66958155/120607395-6c663f00-c450-11eb-923f-4f214ee51e7c.png)

Adjusting my Rserve.conf I can connect to Rserv both without any authentication and with password authentication.

What could be causing the error?

Thanks,
Marcus

**Comment by kimmolinna** [comment]
In some other authentication issue someone mentioned that if you change `auth required` to `auth enable` It can help. At least It's quite easy to try.

**Comment by cljambo** [comment]
Hi kimmolinna,

thanks for the hint. Doesn't work, though. Same error.

Anyone else got an idea?

Regards,
Marcus

**Comment by kimmolinna** [comment]
Hi Marcus,

Have you installed libssl-dev first and then compiled Rserve?
[TLS1.2 support](https://dev.to/sirius93/how-to-enable-t-l-s-1-2-in-r-serve-4ope)

Kimmo

**Comment by s-u** [comment]
Unfortunately, Rserve will fail silently if any of the TLS settings are wrong or if the the TLS support is not present. I have now added at least a warning in case `tls.key` fails in efff0e3 so you should see if your binary doesn't support TLS.

A easy test if TLS is enabled is to use `openssl s_client 127.0.0.1:6312` which should end with:
```
read R BLOCK
Rsrv0103QAP1

--------------
```

**Comment by s-u** [comment]
See also [TLS/SSL support](https://github.com/s-u/Rserve/wiki/TLS-SSL-support), I'll close this as presumed config/build issue, build with SSL and latest version for better TLS status reporting.
