### ISSUE TITLE
Question: How to capture output&message per connection using Java client

### ISSUE THREAD

**Issue by MatthiasHild** [s-u/Rserve#173]
Simon,

We can see all output and messages generated by R from within an RConnection in the stdout and stderr of the process running R.

**Is it possible to capture output and messages separately for each RConnection?**

So far, we only arrived at the somewhat unsatisfactory answer "Yes for output; no for messages"!

Here is what works for **output** (using the [try-eval-parse pattern](http://rforge.net/Rserve/faq.html#errors) you recommend).

For each _.eval_ call to an _RConnection_,

1) If it does not yet exist, create a fifo pipe for this connection on the OS command line (we do this from within Java).
2) Create a new Java thread reading from this pipe. This thread may log etc. Details below but not essential.
3) Assign payload code to variable: connection.assign(".payload.", code); 
4) Sink output to the pipe and evaluate the code: connection.eval(CMD) where CMD is the following string:
> sink(file=PATH_TO_PIPE, append=TRUE, type="output", split=FALSE);
> .result.<-try(eval(parse(text=.payload.)),silent=TRUE);
> sink();
> .result.
5) Tell the reader thread to stop (set flag to break out of _while_ loop).
6) _.join()_ the reader thread.
7) Error if returned _REXP_ _.inherits_ "try-error"; done otherwise.

We may keep the same OS fifo pipe across multiple _.eval_ calls until we close the _RConnection_.

This works for repeated _.eval_ calls and for multiple _RConnections_ on separate Java threads.

What does not work is this:

a) Sink not just output but also messages (_type=c("output", "message")_) - does not redirect stderr.
b) Sink just messages (_type="message"_) - errors with "Error in sink([...] 'file' must be NULL or an already open connection."
c) Sink output and messages to separate pipes (using dedicated Java reader threads) - errors as before.
d) Open and close a fifo connections in R - seemingly non-deterministic behaviour resulting after some iterations in the same error as above. Here the gist of it:
> fd1 <- fifo(out_fname, open = "wt")
> fd2 <- fifo(err_fname, open = "wt")
> sink(file = fd1, type = "output", append=TRUE, split=FALSE)
> sink(file = fd2, type = "message", append=TRUE, split=FALSE)
> ... WORK ...
> sink(type = "output")
> sink(type = "message")
> close(fd1)
> close(fd2)

Of course, there is the ominous warning in the R documentation that could be plucked right from Dante's _Inferno_:

> Do not sink the messages stream unless you understand the source code implementing it and hence the pitfalls.

Help, Simon! Help!

M.

> static protected abstract class AbstractPipeReader extends Thread implements RuntimeCloseable {
> 
> 		public AbstractPipeReader(File pipe, String connectionName) {
> 
> 			super();
> 
> 			this.pipe = pipe;
> 			this.connectionName = connectionName;
> 
> 			setDaemon(true);
> 
> 		}
> 
> 		protected File pipe;
> 
> 		protected String connectionName;
> 
> 		protected AtomicBoolean closed = new AtomicBoolean(false);
> 
> 		@Override
> 		public void run() {
> 
> 			try(RandomAccessFile raPipe = new RandomAccessFile(pipe, "r")) {
> 
> 				String line;
> 
> 				while(!closed.get() && (line = raPipe.readLine()) != null) {
> 
> 					line(line);
> 
> 				}
> 
> 			} catch(IOException e) {
> 				throw new WrappedException(e);
> 			}
> 
> 		}
> 
> 		/*
>  		 E.g. log.info("{}: {}", connectionName, line);
> 		 */ 
> 		protected abstract void line(String line);
> 
> 		@Override
> 		public void close() throws RuntimeException {
> 
> 			closed.set(false);
> 
> 		}
> 
> 	}
>

**Comment by s-u** [comment]
If you want full GUI control, I would strongly recommend the OCAP mode which supports forwarding of everything including console and stdio. Incidentally, I just finished writing up the documentation last week on the [Rserve Wiki: OCAP mode](https://github.com/s-u/Rserve/wiki/OCAP-mode).

The only fly in the ointment is that this is mainly used by JavaScript applications so I have not updated the Java client yet to support OCAP mode. I'll try to do that later today.

**Comment by s-u** [comment]
I have added OCAP and OOB support to the Java client. Minimalistic toy example on possible use:

```r
## single function as capability which does parse + eval
parseEval = function(txt)
 tryCatch(eval(parse(text=txt), .GlobalEnv),
          error=function(e) e)

library(Rserve)
## make parseEval the initial capability
oc.init = function() ocap(parseEval)

## run Rserve with OCAP + OOB enabled
run.Rserve(qap.oc=TRUE, console.oob=TRUE, oob=TRUE)
```

Minimalistic Java client code:

```java
// implement OOBInterface to receive all the output
class TestOOB implements OOBInterface {
    /* OOB API is list(source, [context,] output)
       where context is present if io.use.context is set */
    public void oobSend(int code, REXP message) {
        try {
            RList l = message.asList();
            String src = l.at(0).asString();
            // we only implement the following OOB masseges:
            if (src.equals("console.out") ||
                src.equals("console.err") ||
                src.equals("console.msg") ||
                src.equals("stdout") ||
                src.equals("stderr")) {
                String txt = l.at((l.size() > 2) ? 2 : 1).asString();
                if (src.equals("console.out") || src.equals("stdout"))
                    System.out.print(txt);
                else
                    System.err.print(txt);
            }
        } catch (REXPMismatchException ex) {
            /* if we can't parse it, we ignore it */
        }
    }

    public REXP oobMessage(int code, REXP message) {
        /* we don't implement stdin for now, but it
           would look something like the above */
        return new REXPString("no!\n");
    }
}

/// in main method
           RConnection c = new RConnection();
           // add the OOB handler
            c.setOOB(new TestOOB());
            REXP cap = c.capabilities();
            if (cap == null) {
                System.err.println("ERROR: Rserve is not running in OCAP mode");
                return;
            }
            // we assume the capability is a single function that we want to call
            String testCode = "{ message('Hello!'); print(R.version.string) }";
            RList occ = new RList(new REXP[] { cap, new REXPString(testCode) });
            REXP res = c.callOCAP(new REXPLanguage(occ));
            System.out.println("result: " + res);
```

I don't think I have more time, but someone could probably tie this in with the REngine callbacks...

**Comment by MatthiasHild** [comment]
What a rapid reply! I wish I could have reciprocated but injured my hand.

As is, your example is failing for me. When running the server with _qap.oc=TRUE_, the following error is raised when making an RConnection:

```
 org.rosuda.REngine.Rserve.RserveException: Cannot connect: Handshake failed: expected 32 bytes header, got 16
 	at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:95)
 	at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:65)
 	at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:49)
 	at com.esc.rtest.Oob.rserveOob(Oob.java:114)
 	at com.esc.rtest.Oob.main(Oob.java:36)
 Caused by: org.rosuda.REngine.Rserve.RserveException: Handshake failed: expected 32 bytes header, got 16
 	at org.rosuda.REngine.Rserve.RConnection.initWithSocket(RConnection.java:157)
 	at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:93)
 	... 4 more
``` 
Without _qap.oc=TRUE_, the RConnection succeeds (but, of course, lacks any capabilities).

For this test, the JARs of REngine and Rserve were built from the latest source:

```
<dependency>
	<groupId>org.rosuda.REngine</groupId>
	<artifactId>REngine</artifactId>
<!-- 			<version>2.1.0</version> -->
	<version>2.1.1-SNAPSHOT</version>
</dependency>
<dependency>
	<groupId>org.rosuda.REngine</groupId>
	<artifactId>Rserve</artifactId>
 <!-- 			<version>1.8.1</version> -->
	<version>1.8.2-SNAPSHOT</version>
</dependency>
```
BTW, you should probably **bump** these versions to the next minor (new feature, not patch).

The Rserve package version is the _1.8-8_ snapshot. Here the R session info:

```
 sessionInfo()
 R version 4.1.0 (2021-05-18)
 Platform: x86_64-pc-linux-gnu (64-bit)
 Running under: Ubuntu 16.04.7 LTS
 
 Matrix products: default
 BLAS:   /usr/lib/atlas-base/atlas/libblas.so.3.0
 LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0
 
 locale:
  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
 [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
 
 attached base packages:
 [1] stats     graphics  grDevices utils     datasets  methods   base     
 
 other attached packages:
 [1] Rserve_1.8-8
 
 loaded via a namespace (and not attached):
 [1] compiler_4.1.0
```
I did not pick up on your final comment on "[tying] this in with the REngine callbacks". What do you have in mind? A listener interface on RConnections for stdout and stderr messages? The boilerplate code in your example is already quite small ...

Best wishes,

M.

**Comment by MatthiasHild** [comment]
BTW, GUI control is not my concern but proper log separation in Java. Your solution, however, would work for this goal just as well.

**Comment by s-u** [comment]
@MatthiasHild are you sure you are using the latest sources - when you download Rserve the Java sources are in `Rserve/src/client/java`. When you build the JAR file (just `make`), make sure it includes `org/rosuda/REngine/Rserve/OOBInterface.class` - if not, it doesn't OCAP support.

As for logging - if that's what you are after, I'd use https://github.com/s-u/ulog, Rserve has also built-in ulog support - that is if you want to control the logging as opposed to catching R output.

**Comment by MatthiasHild** [comment]
Simon, 

First about logging. I am only adding that your solution has much broader appeal and more fundamental importance than GUI applications. This is not a big point and should not hold us up - your new OCAP+OOB solution will work! Without using OOB messages, every connection's stdout and stderr is sent to the process running the server. _This_ is information to be logged by Java. The problem is that stdout and stderr from different connections (different java threads) are co-mingled without any identifier of the connection that produced it. `ulog` addresses a quite different need. My failed workaround was the use of inter-process communication via pipes dedicated to individual connections and R's sink function. I expect your OOB solution to be much more efficient, of course.

Second, the problem described (16 byte header error on making connection) is not a missing class (OOBInterface) since my test application using your example compiles correctly. So here details about my build and execution attempts with the request for your corrections.

__REngine & Java Rserve client__

To build REngine and the Java Rserve client, I use `mvn` since these artifacts must end up in my local `.m2` repository for integration into other mavenized projects. `make` yields JARs with the same file structure but slightly different file sizes. (Why are there two competing build systems and why do you use `make` in a Java project that you publish to Maven Central?) If you think it useful, I can manually publish the `make` JARs to `.m2` and try again, but to me this seems to be a quite unlikely source of the problem.

```
git clone https://github.com/s-u/REngine.git
cd REngine/
mvn clean install
cd Rserve/
mvn clean install
```
A note to other readers: [`Rserve/src/client/java`](https://github.com/s-u/Rserve/tree/master/src/client) is a git sub-module pointing at the latest commit of REngine.


__Rserve server__

I get the same behaviour using either your latest published snapshot or a build from source:

_Published snapshot_

The Rserve R package _1.8.-8_ is downloaded from [rforge](http://rforge.net/Rserve/files/) with publication date 2021-07-18 01:28 and md5sum `6995bb93ea4091f8bd18df2ea9330c3f`. This is the same date as your [785d2](https://github.com/s-u/REngine/commit/785d280d66fc496e8aa9028f75f62bccdefc6075) commit to REngine. 

_Build from source_

```
git clone --recurse-submodules https://github.com/s-u/Rserve.git
cd Rserve/
chmod +x mkdist
./mkdist
```
The md5sum of the generated `Rserve_1.8-8.tar.gz` is `77fe4f57a796c865a30fd42009406181`.

__Java client application__

I copy your `TestOOB` class. 

```
static public void main(String[] args) {

	try {

		RConnection c = new RConnection();
		// we never get here - the error occurs when making the connection
		// add the OOB handler
		... Simon's example ...

	} catch(Throwable e) {
		e.printStackTrace();
	}

}
```
__Server instance__

I install the Rserve package (once downloaded, once built from source) and then use your code verbatim. The server seems to start correctly.

When removing the `qap.oc=TRUE` from the `run.Rserve` command, the connection succeeds.

Are there any other diagnostics that might be useful?

Best wishes,

M.

PS: I am excited to switch from my own, 8 year old, parallelizable R re-write and JNI bridge via shared memory to Rserve. The performance is great!

**Comment by s-u** [comment]
Matthias, thanks for the in-depth answer. I was really just asking because I saw your mvn dependency specification which wouldn't work. Using the published RForge snapshot should be the most reliable.

Apparently there was an issue where the first packet could get split into two - this seems to be depended on the OS (it didn't happen on macOS but did on Linux) and timing, so I had to update the Java client to be able to deal with that https://github.com/s-u/REngine/commit/e65ff263cc0b232b56806b6e94ddb4253db8f619

Please try the latest Rserve sources which have the updated REngine.

**Comment by s-u** [comment]
Just for the record, instead of using the in-session option, it is also possible to use the regular Rserve startup via 

```
R CMD Rserve --RS-set qap.oc=1 --RS-set console.oob=1 --RS-set oob=1 \
  --RS-set forward.stdio=1 --RS-source test.R
```
where `test.R` is the above R code without the `run.Rserve` line. I  mention that because by replacing `Rserve` with `Rserve.dbg` in the above it is possible to run the debug version. (Even though that didn't help in this case since the timing of the debug version managed to not split the packet so it just worked :P)

**Comment by MatthiasHild** [comment]
Simon, fantastic! Everything seems to be working correctly now.

I ran a simple test, a test with multiple threads, and finally placed the R instance inside of a docker image (with the OOB solution, I no longer have to capture stdin/stderr of the process running R). 

_Are there any other test you might find useful before a release?_ Please do keep in mind the current violation of the semver convention (minor versions deserve a bump). 

I also hope to run some more heavy integration tests with my existing applications later in the week. Heavy load tests involving the generation of about 500k charts are planned for the coming weeks.

Your last comment "Just for the record, ..." is very useful! I had not been able to figure this out.

Thank you again. I really enjoyed the interaction with you.

M.

**Comment by MatthiasHild** [comment]
Unless you would like me to perform additional tests, we can close this.
