### ISSUE TITLE
TLS/SSL Connection Issues from Tableau Desktop

### ISSUE THREAD

**Issue by tmfbrian** [s-u/Rserve#176]
Hi!

I'm unable to make a SSL connection from Tableau Desktop, non SSL with user name and password authenticates just fine though. I'm using a wildcard certificate with tls.ca defined in the config file. This same wildcard cert is being used to SSL from Tableau Desktop to TabPy, and TabPy runs on the same Windows Server 2019 as Rserve. I have tried many combinations of certs and file extensions for tls.cert and tls.ca. Currently the certbundle.crt file has the wildcard cert (1) and the intermediary certs (2). I've confirmed with openssl that the wildcard certificate I'm using is valid, but I'm unable to setup SSL. Any help would be greatly appreciated, thanks!

**Error message from Tableau Desktop:**
"Analytics extension read operation failed" - no other details included

I've reached out to Tableau Support and they noticed this in the connection logs -
Line 372: {"ts":"2021-08-24T15:03:31.125","pid":4716,"tid":"10cc","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"msg","v":"TLS - failed to add certificate '**_Name of a cert with one of my Domain Controllers listed_**' from store 'Root'. Run: openssl errstr b07c065"}

**Output of the start of Rserve and the connection failure:**

Rserve 1.7-3 () (C)Copyright 2002-2013 Simon Urbanek
$Id$

Loading config file Rserv.cfg
conf> command="remote", parameter="enable"
conf> command="auth", parameter="required"
conf> command="pwdfile", parameter="C:\\path\\userpass.txt"
conf> command="plaintext", parameter="enable"
conf> command="encoding", parameter="utf8"
conf> command="tls.key", parameter="C:\\path\\key.key"
conf> command="tls.cert", parameter="C:\\path\\certbundle.crt"
conf> command="tls.ca", parameter="C:\\path\\certbundle.crt"
conf> command="tls.port", parameter="4912"
conf> command="qap", parameter="disable"
Loaded config file Rserv.cfg
Rserve: Ok, ready to answer queries.
 - create_server(port = 4912, socket = <NULL>, mode = 0, flags = 0x800)
INFO: adding server 00000000024F3D40 (total 1 servers)
INFO: accepted connection for server 00000000024F3D40, calling connected
connection accepted.
sending ID string.

header read result: 16
DUMP [16]: 16 03 01 01 28 01 00 01 24 03 03 fe fa 09 e5 3b  |....(...$......;
resizing input buffer (was 32768, need 16777512) to 16785408
loading buffer (awaiting 16777512 bytes)
malformed packet (n=-1). closing socket to prevent garbage.
done.

**Comment by s-u** [comment]
@tmfbrian Please make sure you have complied Rserve with SSL support (I don't think the Windows version supports SSL so you may need WLS or any unix machine) and also I would strongly recommend using Rserve that is not 8 years old (the current version is 1.8-8). Have a look at #170 it was a discussion with another user trying to setup Tableau. You config looks fine so I suspect you simply don't have SSL support.

**Comment by s-u** [comment]
Assuming this got sorted out - the Windows CRAN binary of 1.8-10 now should support TLS I believe.
