### ISSUE TITLE
Authentication with Rserve failed

### ISSUE THREAD

**Issue by Veerasm** [s-u/Rserve#179]
Hi,

We need your help to resolve authentication failed error as stated below in the attachment (preview).

![image](https://user-images.githubusercontent.com/98412633/151017874-38355a3b-f1e1-49c4-b663-759f1a2f57ca.png)

Error in RS.login (c, "ruser", "Pr0gram1@aws001", authkey = RS.authkey(c)); 
command failed with status code 0x41: authentication failed

Can you please provide guidance to troubleshoot this issue to fix the issue. 

We have verified the pwdfile (credentials- user password) and config , it looks fine.

Thanks
Veera

**Comment by Veerasm** [comment]
Rserve started in debug mode and executed the above command. We could see below output.

Rserve: Ok, ready to answer queries.
 - create_server(port = 6311, socket = <NULL>, mode = 0, flags = 0x0)
INFO: adding server 0x28f3100 (total 1 servers)
 - create_server(port = 6312, socket = <NULL>, mode = 0, flags = 0x800)
INFO: adding server 0x392bf70 (total 2 servers)
INFO: accepted connection for server 0x28f3100, calling connected
connection accepted.
sending ID string.

header read result: 16
DUMP [16]: 06 00 00 00 10 00 00 00 00 00 00 00 00 00 00 00  |................
loading buffer (awaiting 16 bytes)
parsing parameters (buf=0x434c2d0, len=16)
DUMP [16]: 04 0c 00 00 72 73 61 2d 61 75 74 68 6b 65 79 00  |....rsa-authkey.
PAR[0]: 00000010 (PAR_LEN=12, PAR_TYPE=4, large=no, c=0x434c2d0, ptr=0x434c2d4)
CMD=00000006, pars=1
rsa_gen_resp: generating RSA key
 - done
OUT.sendRespData
HEAD DUMP [16]: 01 00 01 00 16 04 00 00 00 00 00 00 00 00 00 00  |................
BODY DUMP [1046]: 00 02 00 00 c4 16 f0 4b fe 6f bc 0d 39 b4 32 ef c0 43 12 a0 f9 11 54 6a 60 73 9e 21 5a 8d 29 23 c3 fc ad 64 10 10 85 35 fc 0b 3c 0d 73 b0 e2 c5 c8 a8 8d fd dc cd 21 a6 b8 f2 39 9d 15 8d 91 3c 4c 82 1e ba a7 4c 38 40 21 db bd f4 f2 3b 94 bd 3d 39 a6 b7 24 eb 38 1f e8 48 e1 11 a1 20 5b ab 36 26 54 28 b9 e5 8a 0f bb e5 40 73 ad f3 0c 72 9b 0d e8 ca d7 b1 b1 d8 a3 fe d6 f7 b3 88 12 33 28 ...  |.......K.o..9.2..C....Tj`s.!Z.)#...d...5..<.s.........!...9....<L....L8@!....;..=9..$.8..H... [.6&T(......@s...r...............3(

header read result: 16
DUMP [16]: 07 00 00 00 04 04 00 00 00 00 00 00 00 00 00 00  |................
loading buffer (awaiting 1028 bytes)
parsing parameters (buf=0x434c2d0, len=1028)
DUMP [1028]: 05 00 04 00 97 1e dd db 2b 83 f8 b0 07 50 32 56 74 43 5d 8e 13 37 b5 6a 7b e3 2c e2 68 71 81 a3 ba ae 8e de 02 ce 38 29 5a ae 75 1f cc a9 ec 1b c0 cb ba 4f 43 bc 61 dd 3f fa 18 43 14 b1 07 83 55 1a 2e 97 86 4c 6b 9a 12 b8 f0 bc c2 15 78 61 f6 f8 5c df 14 71 f6 78 6a a3 ac ae b2 61 c3 97 6c 96 7a 17 2e 07 ef bf 4b 7c 54 5a eb 76 0f 17 b9 76 ff e3 94 da 04 0a d1 0b 8c fb 9f 49 e1 0a 60 ...  |........+....P2VtC]..7.j{.,.hq........8)Z.u........OC.a.?..C....U....Lk.......xa..\..q.xj....a..l.z.....K|TZ.v...v...........I..`
PAR[0]: 00000404 (PAR_LEN=1024, PAR_TYPE=5, large=no, c=0x434c2d0, ptr=0x434c2d4)
CMD=00000007, pars=1
CMD_secLogin: authkey matches, asl payload: 23
Authentication attempt (login='ruser', pwd='Pr0gram1@aws001', pwdfile='/usr/Rserve/passwordfile ')
OUT.sendRespData
HEAD DUMP [16]: 02 00 01 41 00 00 00 00 00 00 00 00 00 00 00 00  |...A............
(no body)
INFO: accepted connection for server 0x28f3100, calling connected
connection accepted.
sending ID string.

header read result: 16
DUMP [16]: 01 00 00 00 1c 00 00 00 00 00 00 00 00 00 00 00  |................
loading buffer (awaiting 28 bytes)
parsing parameters (buf=0x434c2d0, len=28)
DUMP [28]: 04 18 00 00 72 75 73 65 72 0a 50 72 30 67 72 61 6d 31 40 61 77 73 30 30 31 00 00 00  |....ruser.Pr0gram1@aws001...
PAR[0]: 0000001c (PAR_LEN=24, PAR_TYPE=4, large=no, c=0x434c2d0, ptr=0x434c2d4)
CMD=00000001, pars=1
Authentication attempt (login='ruser', pwd='Pr0gram1@aws001', pwdfile='/usr/Rserve/passwordfile ')
OUT.sendRespData
HEAD DUMP [16]: 02 00 01 41 00 00 00 00 00 00 00 00 00 00 00 00  |...A............
(no body)

**Comment by s-u** [comment]
@Veerasm your password file `/usr/Rserve/passwordfile` does not contain any valid entries. Make sure it is readable and has the corresponding entry. From your attempt is means it shold have either

```
ruser Pr0gram1@aws001
```
or more securely
```
ruser $882851c6a4d3b06bc1a40476b37e932be40f8d8a
```

**Comment by Veerasm** [comment]
Thanks for your advice.  I am still getting authentication failed error even after correcting the pwd file.

Error:
 
_RS.login(c, "ruser", "Pr0gram1@aws001", authkey=RS.authkey(c));
Error in RS.login(c, "ruser", "Pr0gram1@aws001", authkey = RS.authkey(c)) :
  command failed with status code 0x41: authentication failed_

Output in Debug log: There is no space now at the end of the file name.

header read result: 16
DUMP [16]: 06 00 00 00 10 00 00 00 00 00 00 00 00 00 00 00  |................
loading buffer (awaiting 16 bytes)
parsing parameters (buf=0x2d0d2d0, len=16)
DUMP [16]: 04 0c 00 00 72 73 61 2d 61 75 74 68 6b 65 79 00  |....rsa-authkey.
PAR[0]: 00000010 (PAR_LEN=12, PAR_TYPE=4, large=no, c=0x2d0d2d0, ptr=0x2d0d2d4)
CMD=00000006, pars=1
rsa_gen_resp: generating RSA key
 - done
OUT.sendRespData
HEAD DUMP [16]: 01 00 01 00 16 04 00 00 00 00 00 00 00 00 00 00  |................
BODY DUMP [1046]: 00 02 00 00 22 11 8f 51 5f 58 9e 25 8c 87 79 fe f5 40 0e d7 54 32 de 6a 99 92 65 52 26 3b 86 45 ce 44 d6 3f d3 48 ee de fc 83 16 66 5d 96 29 e6 5b 6a 8d 2e b4 7c 10 e8 38 fe 46 57 9e aa 5b 56 22 71 bf 0d 5d 22 78 67 ef dc 18 de 26 54 9a 30 22 63 86 2f 2c 7b b6 44 92 55 31 b8 67 b0 3d f1 ed 93 99 bd b1 59 34 08 a0 90 33 19 ed 57 2f e2 28 52 4c 13 f0 e9 5d 79 58 1f 6a 6e 41 06 01 b3 da ...  |...."..Q_X.%..y..@..T2.j..eR&;.E.D.?.H.....f].).[j...|..8.FW..[V"q..]"xg....&T.0"c./,{.D.U1.g.=......Y4...3..W/.(RL...]yX.jnA....

header read result: 16
DUMP [16]: 07 00 00 00 04 04 00 00 00 00 00 00 00 00 00 00  |................
loading buffer (awaiting 1028 bytes)
parsing parameters (buf=0x2d0d2d0, len=1028)
DUMP [1028]: 05 00 04 00 0a d5 65 a5 d4 69 1f 0c 10 4b 76 0d c4 0f 03 31 04 6d a6 c7 7d f6 6d 52 5c 68 9f cf 92 60 e3 ca 3b 99 18 70 3b 66 f7 3f ee 77 5c 4c 18 64 2e 2c 1a 66 5d 27 90 a6 ef d3 d0 fa d3 35 d9 bc 33 4e 97 b4 ea 52 32 35 2f 42 ce 80 6c 31 9b 6e f4 51 78 3c 8f 31 e2 2c b7 06 fd 39 14 14 0b c0 46 ce d5 18 80 68 6c 62 0e e4 fb 90 05 a9 eb d7 28 ee 9c 4b 6f 34 ad d4 c0 70 01 eb a9 6d c2 ...  |......e..i...Kv....1.m..}.mR\h...`..;..p;f.?.w\L.d.,.f]'.......5..3N...R25/B..l1.n.Qx<.1.,...9....F....hlb........(..Ko4...p...m.
PAR[0]: 00000404 (PAR_LEN=1024, PAR_TYPE=5, large=no, c=0x2d0d2d0, ptr=0x2d0d2d4)
CMD=00000007, pars=1
CMD_secLogin: authkey matches, asl payload: 23
Authentication attempt (login='ruser', pwd='Pr0gram1@aws001', pwdfile='/usr/Rserve/passwordfile')
OUT.sendRespData
HEAD DUMP [16]: 02 00 01 41 00 00 00 00 00 00 00 00 00 00 00 00  |...A............
(no body)
INFO: accepted connection for server 0x12b4100, calling connected
connection accepted.
sending ID string.

header read result: 16
DUMP [16]: 01 00 00 00 1c 00 00 00 00 00 00 00 00 00 00 00  |................
loading buffer (awaiting 28 bytes)
parsing parameters (buf=0x2d0d2d0, len=28)
DUMP [28]: 04 18 00 00 72 75 73 65 72 0a 50 72 30 67 72 61 6d 31 40 61 77 73 30 30 31 00 00 00  |....ruser.Pr0gram1@aws001...
PAR[0]: 0000001c (PAR_LEN=24, PAR_TYPE=4, large=no, c=0x2d0d2d0, ptr=0x2d0d2d4)
CMD=00000001, pars=1
Authentication attempt (login='ruser', pwd='Pr0gram1@aws001', pwdfile='/usr/Rserve/passwordfile')
OUT.sendRespData
HEAD DUMP [16]: 02 00 01 41 00 00 00 00 00 00 00 00 00 00 00 00  |...A............
(no body)

**Comment by s-u** [comment]
@Veerasm please see previous response - I can't check your system for you, your file is either not readable or does not have a valid entry. Please see documentation the for details.

**Comment by Veerasm** [comment]
Thanks. File has valid entry and able to access with mentioned credentials in password file. permissions are also seems fine. 
Please see the attached screen for details. 

[Prime] root@:/usr/Rserve # ls -ltr
total 4
drwxrwxr-x 2 root  root    6 Nov 30 12:41 workspace
drwxrwxr-x 2 root  root  126 Dec 17 11:19 CA
-rwxrwxrwx 1 ruser users  23 Jan 26 09:06 passwordfile

[Prime] root@:/usr/Rserve # more passwordfile
ruser Pr0gram1@aws001

![image](https://user-images.githubusercontent.com/98412633/151167024-52055276-8f36-49d3-af33-4e70541df954.png)

Permission for password file is as below

-rwxrwxrwx 1 ruser users  23 Jan 26 09:06 passwordfile

Permission for the content in /usr directory is as below.

[Prime] root@:/usr # ls -ltr
total 164
drwxr-xr-x   2 root root     6 Jun 27  2017 games
drwxr-xr-x   3 root root    22 Jun 27  2017 src
drwxr-xr-x   3 root root    19 Feb 26  2020 X11R6
drwxr-xr-x   5 root root    43 Feb 26  2020 x86_64-suse-linux
lrwxrwxrwx   1 root root    10 Feb 26  2020 tmp -> ../var/tmp
drwxr-xr-x   6 root root    61 Oct 14 14:53 sap
drwxr-xr-x  14 root root   156 Oct 14 14:55 local
drwxr-xr-x  62 root root  4096 Oct 18 10:10 lib
drwxr-xr-x   2 root root 16384 Oct 18 10:11 sbin
drwxr-xr-x 108 root root  4096 Oct 18 17:34 share
drwxr-xr-x  55 root root 40960 Oct 19 14:39 lib64
drwxr-xr-x  84 root root  8192 Oct 19 14:39 include
drwxr-xr-x   2 root root 36864 Jan 19 21:16 bin
drwx------   4 root root    53 Jan 26 09:06 Rserve
[Prime] root@:/usr # ls -ld
drwxr-xr-x 15 root root 192 Nov 30 12:41 .
[Prime] root@:/usr #

It seems permission are correct as per the documentation. Could you please advice any changes/permission are required to any specific folder or file.

I tried to execute the command with both users root and ruser but still still getting authentication failed error.

**Comment by s-u** [comment]
The permissions aren't correct see:
```
drwx------ 4 root root 53 Jan 26 09:06 Rserve
```

**Comment by Veerasm** [comment]
Thanks Simon. Authentication is working fine. But, issue is still there as Rserve is not working as expected. 

I could see following error when Rserve was started.

Rserv started in daemon mode.
> Error in py_call_impl(callable, dots$args, dots$keywords) :
  NotImplementedError: Cannot convert a symbolic Tensor (lstm_5/strided_slice:0) to a numpy array.

Detailed traceback:
  File "/home/ruser/.local/share/r-miniconda/envs/r-reticulate/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/model_config.py", line 96, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "/home/ruser/.local/share/r-miniconda/envs/r-reticulate/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 102, in deserialize
    printable_module_name='layer')
  File "/home/ruser/.local/share/r-miniconda/envs/r-reticulate/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 191, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/ruser/.local/share/r-miniconda/envs/r-reticulate/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 370, in from_config
    model.add(layer)
  File "/home/ruser/.loc

 could you please suggest.

**Comment by Veerasm** [comment]
There is an error message at application level. Please see below.

Call R procedureA database error occured. The error message in the database was: "column store error: search table error:  [34082] Execution of R script failed;Error in py_call_impl(callable, dots$arg

**Comment by s-u** [comment]
Sorry, that has nothing to do with Rserve, please consult the documentation of the R and Python functions you are using.
