### ISSUE TITLE
declared variables not retrievable

### ISSUE THREAD

**Issue by philperrin** [s-u/Rserve#180]
Hi there - 
I must have taken a wrong turn somewhere because in my latest install using Rserve, whenever I declare a variable (ie, x <- 42), I am unable to retrieve it (later calling 'x' returns an error: "object 'x' not found").

For reference, I am using this as a Tableau extension, from a Linux box. The connection is otherwise fine, I can see everything loading and computing in terminal look normal. 

Happy to share config settings, etc - but I wasn't sure if there is a known flag or typical cause for variables to be computed but not stored.

Thanks in advance.

Phil

**Comment by s-u** [comment]
Sorry, I have no idea what Tableau extension does so please contact their support. It could be that they evaluate code in a local environment environment or similar, no way for us to know - so not really an Rserve question. As long as the client holds the connection it is talking to the same R process, so all regular R rules apply.

**Comment by philperrin** [comment]
Thanks for the follow up @s-u !
I think I determined what was happening in the meantime. The situation pertains to values stored in memory which I cannot quite nail down the logic. I am now writing the results of each calculation to an output file so that subsequent queries can reference the output file. I had been relying on any declarations to be persistent but that appears to not generally be the case.
Very much appreciate all your work on this tool!

**Comment by s-u** [comment]
@philperrin in R the variables are definitely persistent as long as it a single connection. To avoid issues with local evaluation you can try `x <<- ...` or `.GlobalEnv$x <- ...`. If that doesn't work then you need to talk to Tableau as that would mean that they close the connection after one evaluation.
