### ISSUE TITLE
Need some Help with Rserve and SSL

### ISSUE THREAD

**Issue by JerryDiLeo** [s-u/Rserve#183]
Hi All,

I keep getting the following message when trying to enable SSL with Rserve;

WARNING: setting tls.key FAILED, TLS will NOT be used (TLS support is not present, you may need to re-compile with OpenSSL)

My Linux Admins have added libssl removed RServe package and re-added but can't get past this error.  Can you let me know the steps we need to take to recompile with OpenSSL so I can be sure we added properly? 

Red Hat Enterprise Linux Server release 7.9

Thanks for the assistance,

**Comment by s-u** [comment]
Please make sure you install `libssl-devel` (`lib-ssl` alone is NOT sufficient!) and re-install. When you are re-installing make sure you watch the output - you should see something like:

```
checking for openssl/rsa.h... yes
checking for library containing RSA_generate_key... -lcrypto
checking for openssl/ssl.h... yes
checking for library containing SSL_CTX_load_verify_locations... -lssl
```

**Comment by JerryDiLeo** [comment]
Hi Simon,

Thank you for your response, we actually
have openssl-devel-1.0.2k-24.el7_9.x86_64 installed, is this sufficient?
This was the output from last weeks install

[image: image.png]
[image: image.png]

Appreciate the assistance,


Jerry DiLeo


Senior Applications Administrator
NYU IT - Data Infrastructure Services

105 East 17th St, 4th Fl.
(212)998-1146

**Comment by s-u** [comment]
Please don't use images - they don't work. If appropriate just copy/paste output (in backtick sections) if you wish. Also note that if some tests fail, you can look at the `config.log` file which will have more details on what which commands failed exactly and what are the errors.

**Comment by JerryDiLeo** [comment]
My Linux Admin installed openssl-devel does that meet the requirements or does libssl-devel need to be installed as well.

Here's my output:

checking for openssl/rsa.h... yes
checking for library containing RSA_generate_key... -lcrypto
checking for openssl/ssl.h... yes
checking for library containing SSL_CTX_load_verify_locations... -lssl

Thanks for taking a look

**Comment by s-u** [comment]
The above output suggests that SSL should work.

**Comment by JerryDiLeo** [comment]
Hi,

Sorry for the delay I was out of the office, l am seeing the
following error messages even though output seems to suggest SSL is ok?

"WARNING: setting tls.key FAILED, TLS will NOT be used (TLS support is not
present, you may need to re-compile with OpenSSL)"

Would this message appear if there was an issue with certs like for
instance not pointing to the correct tls.ca? I have the tls.key and
tls.cert defined but not too sure what to use for the tls.ca.  Or does
this error suggest there is still an issue occurring before reading the
certs?

Thanks for the help,



Jerry DiLeo


Senior Applications Administrator
NYU IT - Data Infrastructure Services

105 East 17th St, 4th Fl.
(212)998-1146

**Comment by s-u** [comment]
The error really means that the binary you use has no TLS support. If the key itself failed it would say "check your key file" instead.

How do you start Rserve? Perhaps you have multiple binaries around and you are starting the old one with no TLS support?

**Comment by JerryDiLeo** [comment]
When I start using the following method,   R CMD Rserve it gives me the
error.




Jerry DiLeo


Senior Applications Administrator
NYU IT - Data Infrastructure Services

105 East 17th St, 4th Fl.
(212)998-1146

**Comment by s-u** [comment]
As mentioned earlier - do NOT use attachments, they don't make it. Use copy/paste. You should use `Rserve::Rserve()` (with the corresponding options) to start it. If you want in-session Rserve then you can use `Rserve::run.Rserve()`.

**Comment by JerryDiLeo** [comment]
Thanks for the recommendation, I started it up using
the Rserve::run.Rserve() options and am seeing the SSL ports running
without the SSL error message.  I will have my development team test to see
if they can access the servers and will keep you posted.

Thanks again for your assistance.


Senior Applications Administrator
NYU IT - Data Infrastructure Services

105 East 17th St, 4th Fl.
(212)998-1146

**Comment by JerryDiLeo** [comment]
Thanks for all the assistance, it's running with SSL.




Jerry DiLeo


Senior Applications Administrator
NYU IT - Data Infrastructure Services

105 East 17th St, 4th Fl.
(212)998-1146

**Comment by s-u** [comment]
Great!
