### ISSUE TITLE
"Ignoring SIGPIPE signal" only when Rserve daemon is started from the server program

### ISSUE THREAD

**Issue by borjaevo** [s-u/Rserve#184]
I have some functions to manage the Rserve daemon state from the user interface (java backend, debian). This way the user can see if Rserve is running and start the daemon from the GUI if necessary. There is a very simple instruction for starting:
`List<String> args = List.of("/bin/sh", "-c","echo 'library(Rserve);Rserve(args=\"--no-save --slave\");'| /usr/lib/R/bin/R --no-save --slave");`

This works ok most of the time, but in some cases that depends on the data R is processing the program stops like this: 
`Error: Error in cat(conditionMessage(c), file = stderr(), sep = "") : 
  ignoring SIGPIPE signal`

But i have noticed when executing exactly the same program with the same data but i started Rserve manually, it completes ok. This process is:
1- start R
2- load Rserve libary
3 start Rserve with the instruction Rserve()

Then it loads all libraries i have in the "/etc/Rserv.conf" file like when the user starts the daemon from the user interface. I only have one Rserv.conf file. 

What could be the difference?
Thanks!

**Comment by s-u** [comment]
`SIGPIPE` means that an output pipe is unable to write output. Typically, it means that R cannot write to `stdout` or `stderr`, because you have failed to bind the descriptors to receivers.  Please see https://github.com/s-u/REngine/blob/master/Rserve/StartRserve.java for an example how to start Rserve from Java.

**Comment by borjaevo** [comment]
Thanks for the info about starting Rserve, i did my own implementation of that but looking at the code is pretty much the same. I dont think this is the problem because its not like it does not run every time but with some data it fails. And with this same data if i have started Rserve manually it works. 
I have to clarify that with other data all the functions that im using works without problem even using the auto-start (lmer, emeans, etc). I thought about maybe some limits or the load order of the libraries.... i dont know...

**Comment by s-u** [comment]
@borjaevo are you sure your code starts the I/O threads to accept the output from the R streams? That is the important part which prevents `SIGPIPE`. You didn't share the full code, but the pieces you shared wouldn't work for the above reasons.

**Comment by borjaevo** [comment]
Thank you very much, you're right, that could be the issue. I will try to start Rserve using your example code and see if it works.

**Comment by borjaevo** [comment]
I've changed the start method as you said and seems to be working better. Closed, thanks!
