### ISSUE TITLE
improved feedback?

### ISSUE THREAD

**Issue by eduarddrenth** [s-u/Rserve#189]
Dear all,

Would it be an idea to invest in improving feedback from `eval("source(\""+someScript+"\")");`

At the moment I assign a path to an error file before calling eval. In the script I write errors to this file. When eval returns erroneously I read errors from this file.

This however does not cover all problems. My last resort at the moment:

`Script failed, you may need to use cat "/proc/PID of Rserve/fd/2" and repeat the request to find what is wrong.`

Perhaps extending RserveException with (truncated) info would be an option.

Or perhaps there already is a better way to handle faults already that I missed.

Greetings, Eduard

**Comment by s-u** [comment]
It's not entirely clear to me what you intended, but perhaps have look at [Rserve.eval](https://rforge.net/Rserve/docs/reference/Rserve.eval.html) which generates objects that contain the errors, condition objects and tracebacks on error. It is really up to you to define what you want to happen in those cases. Also I would recommend using the [OCAP mode](https://github.com/s-u/Rserve/wiki/OCAP-mode) if you are interested in the output as well.

**Comment by eduarddrenth** [comment]
perhaps this helps, I'll have a look
