### ISSUE TITLE
HOWTO: set the working directory of daemonized R CMD Rserve process

### ISSUE THREAD

**Issue by malcook** [s-u/Rserve#193]
in [\[Rd\] using R as SHELL in gnu make](https://lists.gnu.org/archive/html/help-make/2014-02/msg00003.html) @s-u wrote:

>  the daemon version of Rserve changes 
> the working directory to / as part of the daemonization process, so you won't 
> get to pwd in that case. One way to deal with that is to use in-R Rserve 
> process, e.g. start it via
> 
> Rscript -e 'Rserve::run.Rserve(workdir="",socket=".rs-socket")'
> 
> then you'll and up in the working directory.

Indeed, I find this to be the case.  Yet I still wonder:

Is there way of setting the working directory for a Rserve daemonized with `R CMD`?

For instance,  I have tried...

` R CMD Rserve --RS-socket /path/to/project/.rs-socket --RS-pidfile /path/to/project/.rs-pid --RS-set $"eval=setwd('/path/to/project'); print(getwd())"
`

...which does set the working directory but the change does not persist.

Similarly, I have to no avail tried setting it in the loaded .Rprofile.

Relatedly, do I understand correctly that if `control` was still supported I could acheive this with:
`
RS.server.eval(rsc, "setwd('/path/to/project')")
`

**Comment by s-u** [comment]
Setting working directory to `/` is standard behavior for daemons - from `man 7 daemon`:

       11. In the daemon process, change the current directory to the
           root directory (/), in order to avoid that the daemon
           involuntarily blocks mount points from being unmounted.

But it's not clear to me what exactly you are trying to achieve, since the working directory of the daemon is usually irrelevant as connections get their own, individual working directories, so the deamon's one doesn't matter to client connections.

**Comment by malcook** [comment]
I am trying to create an RServe process wherein all expressions evaluated remotely using RSclient::RS.eval  are evaluated with a pre-determined working directory _without having to first evaluate setwd for each and every connection_.

I can achieve this if I create the process using:

`
  Rscript -e $"Rserve::run.Rserve(workdir='',socket='.rs-socket pid.file='${RS_PIDFILE}')"  
`

It works for me since the process created by Rscript prior to evaluting the call the run.Rserve has an established working directory which is inherited by the Rserve process.

**Comment by s-u** [comment]
Ok, got it, so you are disabling workdirs. In that case, the only option is to not let Rserve daemonize, i.e. set `--RS-set daemon=no`. On most unix systems there are tools that allow you to daemonize processes, but beware, because they typically follow the same rules (i.e. change work dir to `/`). They may have options to override that, e.g. `demonize` supports `-c` to set the directory you want to run it in instead of `/`.

**Comment by malcook** [comment]
Thanks for pointing out `--RS-set daemon=no`.

So, the answer to my first question of:

> Is there way of setting the working directory for a Rserve daemonized with R CMD?

appears to be:

No.  But...

... I can put into the background an Rserve process created without daemonization (with ` --RS-set daemon=no` ) which in combination with disabling working directory management (with  `--RS-workdir '' `) and server-side sourcing of .Rprofile (with `--RS-source` ${PWD}/.Rprofile) provides my desired behavior.

In short:

```
nohup R CMD Rserve --vanilla \
--RS-socket ${RS_SOCKET} --RS-pidfile ${RS_PIDFILE}  \
--RS-workdir '' --RS-set daemon=no  \
--RS-source ${PWD}/.Rprofile &
```

And, an approach to my second question:

> Is there a way to ... wait until the (Rserve process) is done initializing (loading/sourcing/evaling/listening) before proceeding. 

...can be had by arranging for a flag file to be set within the Rserve process and waiting for it in the calling process, e.g.:

```
nohup R CMD Rserve --vanilla \
--RS-socket ${RS_SOCKET} --RS-pidfile ${RS_PIDFILE}  \
--RS-workdir '' --RS-set daemon=no  \
--RS-source ${PWD}/.Rprofile \
--RS-set eval=$"file.create('${RS_PIDFILE}.initialized')" &
while [ ! -f ${RS_PIDFILE}.initialized ]; do sleep 1; done
rm ${RS_PIDFILE}.initialized
```
