### ISSUE TITLE
Rserve daemon crashes with Java client

### ISSUE THREAD

**Issue by misek-7** [s-u/Rserve#27]
Hi,

I run Rserve in daemon mode in Linux environment and use the REngine Java client to connect the server. My problem is the following: 
* First I initialize a session with voidEvalDetach
* I load a package in the R code with the library command
* When I try to reconnect the session, the daemon stops without error

The reconnection works with simple code, but complex codes seems to cause problem.

**Comment by s-u** [comment]
Can you elaborate on the actual code used? The daemon (=Rserve process) is not involved in re-connecting client sessions since they listen on a separate port. Please post an example so we can reproduce.

**Comment by s-u** [comment]
Not reproducible/incomplete.
