### ISSUE TITLE
Publish Rserve Java Client to Maven Central

### ISSUE THREAD

**Issue by cemmersb** [s-u/Rserve#3]
Dear all - Is there a chance to publish the java client continuously to maven central?
Currently there are older releases published at the repository and I was wondering, if the good work could be made available more consistently (http://search.maven.org/#search%7Cga%7C1%7CREngine)

Beside that, it would be nice having an OSGi bundle to put the RServe and REngine environments into an OSGi container. I've started some work based on a maven build. The Build creates a single output bundle containing all packages.
If you are interested, you can see the current status here: https://github.com/cemmersb/RCode

Please let me know, if you have considered the options of
(a) having a build in place that provisions the artifacts to the central maven repository
(b) creating an OSGi bundle to support OSGi environments

Point (b) could be also achieved via the current project build with a small addition of an OSGi MANFEST file.

Kind regards,

Christoph

**Comment by vasvir** [comment]
+1 for this

**Comment by antonkulaga** [comment]
Any progress with publishing?
Publishing to maven/bintray is such a common practise in scala/java world that RServe is the only library that I use as jar, everything else is resolved form maven/bintray/etc

**Comment by s-u** [comment]
Now on Maven Central (`org.rosuda.REngine:REngine:2.1.0` and `org.rosuda.REngine:Rserve:1.8.1`), REngine source now also contain the corresponding `pom`s so it is ready for continuous publishing.
(FWIW I didn't have time to port the tests yet.)

**Comment by tomas-pluskal** [comment]
This is great news. Thanks a lot!

**Comment by s-u** [comment]
Thanks to everyone here, in particular @cemmersb for converting the Rserve tests - they are now in as well. Please use the REngine repo for further discussion, suggestions etc.

**Comment by tomas-pluskal** [comment]
I don't want to sound too greedy, but since now we have REngine and RServe, is there also a plan to publish JRIEngine to Maven Central?

**Comment by s-u** [comment]
The trouble there is the JNI part and dependency on R. The binaries would depend on both R version and the platform. If you have any ideas how to deal with that in Maven, let me know.

**Comment by tomas-pluskal** [comment]
Is it possible to add the JRIEngine's java classes (jars) to Maven Central, and let the users download the corresponding native libraries separately?
