### ISSUE TITLE
install.packages('Rserve',,'http://www.rforge.net/') fails with undefined reference to `pthread_atfork'

### ISSUE THREAD

**Issue by mbacou** [s-u/Rserve#30]
CentOS release 6.6 (Final) 64bit
R version 3.2.0 

Trying to install Rserve from rforge.net, but fails with error below. Thanks for any tip.

```
install.packages('Rserve',,'http://www.rforge.net/')
[...]
/tmp/ccPjMmJS.o: In function `ioc_setup':
/tmp/Rtmp5OW6HC/R.INSTALL172242400c61/Rserve/src/ioc.c:187: undefined reference to `pthread_atfork'
collect2: ld returned 1 exit status
make: *** [server] Error 1
ERROR: compilation failed for package ‘Rserve’
* removing ‘/usr/lib64/R/library/Rserve’

```

**Comment by mbacou** [comment]
Ignore, I had Rserve v1.7-3 already installed.

**Comment by mbacou** [comment]
Actually I am somewhat confused trying to upgrade Rserve. There is no Rserve package found but `R CMD Rserve` does work?

```
> remove.packages("Rserve")
Removing package from ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
Error in find.package(pkgs, lib) : there is no package called ‘Rserve’
> q()
Save workspace image? [y/n/c]: n
[mbacou@481266 ~]$ R CMD Rserve --version
Rserve v1.7-3 ()
R version 3.2.0 (2015-04-16) -- "Full of Ingredients"
```

**Comment by s-u** [comment]
`R CMD Rserve` runs whatever binary you have installed in `${RHOME}/bin` (or on your `PATH`), it is entirely independent of the package.

As for your original question (failure due to pthreads) please set
```r
Sys.setenv(PKG_LIBS="-pthread")
```
it seems that the detection of pthread flags in `configure` doesn't work on some systems.

**Comment by kurraraghu** [comment]
install.packages('Rserve', repos='http://www.rforge.net/',type="source")

**Comment by karolsarnacki** [comment]
@s-u Sorry for re-opening such an old thread, but I'm getting the same error as mbacou.

I'm trying to install Rserve on Heroku (using this buildpack: https://github.com/virtualstaticvoid/heroku-buildpack-r). The error I'm getting is:

```
       /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
       (.text+0x12): undefined reference to `__libc_csu_fini'
       (.text+0x19): undefined reference to `__libc_csu_init'
       /tmp/ccjfGQuE.o: In function `ioc_setup':
       /tmp/RtmpuxMCa7/R.INSTALL58279945f8e/Rserve/src/ioc.c:187: undefined reference to `pthread_atfork'
       collect2: error: ld returned 1 exit status
       Makevars:12: recipe for target 'server' failed
       make: *** [server] Error 1
       ERROR: compilation failed for package ‘Rserve’
```

Here is my `init.R` file used to install the dependencies:

```R
Sys.setenv(PKG_LIBS="-pthread")
install.packages("Rserve", repos = "http://rforge.net")
```

I also tried to set `PKG_LIBS` with Heroku env variables.

**Comment by karolsarnacki** [comment]
@s-u Sorry to bother you, but could you briefly look at the above error?

**Comment by s-u** [comment]
@karolsarnacki sorry, I cannot help you until you post details that would allow me to see what's the problem. At the very least you have to post the full `config.log` file as well as exact details about the OS you are using. The pthread test is actually the official `AX_PTHREAD` from autoconf which does include `pthread_atfork` test.

**Comment by s-u** [comment]
This is rather odd - the `pthread` test succeeds without any flags:

```
checking whether threads are desired... yes
checking for working threads support... checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... yes
```

yet on your system it doesn't actually work.

I think you should be able to work around it by setting `PKG_LIBS=-pthread`, but I wonder why the first test succeeds. For comparison a real Ubuntu 18.04 yields:

```
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
```

**Comment by karolsarnacki** [comment]
The logs that I pasted were generated with `PKG_LIBS=-pthread` already set. I set it with ENV variables on Heroku, but also in R itself, with `Sys.setenv(PKG_LIBS = "-pthread")` command. But maybe for some reason, the system still does not see the setting? 🤔

**Comment by s-u** [comment]
Oh, hold on, you're right - there is `-pthread` in both compilations! So something is rather fundamentally broken on that OS .. you'll have to find out why pthreads are broken on that machine. It may be that more is broken since there is that CRT error as well. I fear this has nothing to do with Rserve but rather the compilation environment on the machine is broken. You may have more luck on Heroku mailing lists to find out if there is something missing in that setup ... If you need special flags, you can always add them to `PKG_LIBS` like you did or `PKG_CPPFLAGS` - it's just you may need to find out what to add and/or install. The system is not "real" Ubuntu 18.04 since that one works out of the box.
One idea - try also setting `PKG_CPPFLAGS=-pthread` as a last resort...

**Comment by karolsarnacki** [comment]
Unfortunately, setting `PKG_CPPFLAGS=-pthread` did not work, either... Anyway, thank a lot for your help, I'll try to contact Heroku support as you suggested!
