### ISSUE TITLE
Rserve install error

### ISSUE THREAD

**Issue by ayjung** [s-u/Rserve#40]
Red Hat Enterprise Linux Server release 6.3 (Santiago)
R version 3.2.2 

Trying to install Rserve from rforge.net, but fails with error below. Thanks for any tip.

> install.packages("/usr/lib64/R/library/Rserve_1.7-3.tar.gz", repos = NULL, type = "source")
> R CMD INSTALL Rserve_1.7-3.tar.gzInstalling package into ‘/home/R/x86_64-redhat-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
* installing *source* package ‘Rserve’ ...
** package ‘Rserve’ successfully unpacked and MD5 sums checked
checking whether to compile the server... yes
checking whether to compile the client... no
checking for gcc... gcc -m64 -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -m64 -std=gnu99 accepts -g... yes
checking for gcc -m64 -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -m64 -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for string.h... (cached) yes
checking for memory.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking for sys/types.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/un.h usability... yes
checking sys/un.h presence... yes
checking for sys/un.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking netinet/tcp.h usability... yes
checking netinet/tcp.h presence... yes
checking for netinet/tcp.h... yes
checking for an ANSI C-conforming const... yes
checking whether byte ordering is bigendian... no
checking whether time.h and sys/time.h may both be included... yes
checking for pid_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking return type of signal handlers... void
checking for memset... yes
checking for mkdir... yes
checking for rmdir... yes
checking for select... yes
checking for socket... yes
checking for srandomdev... no
checking for library containing crypt... -lcrypt
checking crypt.h usability... yes
checking crypt.h presence... yes
checking for crypt.h... yes
checking for socklen_t... yes
checking for connect... yes
checking whether to enable IPv6... no
checking for dlopen in -ldl... yes
checking openssl/rsa.h usability... yes
checking openssl/rsa.h presence... yes
checking for openssl/rsa.h... yes
checking for library containing RSA_generate_key... -lcrypto
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for library containing SSL_CTX_load_verify_locations... -lssl
configure: creating ./config.status
config.status: creating src/Makevars
config.status: creating src/client/cxx/Makefile
config.status: creating src/config.h
** libs
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c RSserver.c -o RSserver.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c Rserv.c -o Rserv.o
Rserv.c: In function ‘prepare_set_user’:
Rserv.c:372: warning: ignoring return value of ‘chown’, declared with attribute warn_unused_result
Rserv.c:375: warning: ignoring return value of ‘chown’, declared with attribute warn_unused_result
Rserv.c: In function ‘Rserve_QAP1_connected’:
Rserv.c:2342: warning: ignoring return value of ‘chdir’, declared with attribute warn_unused_result
Rserv.c:3351: warning: ignoring return value of ‘chdir’, declared with attribute warn_unused_result
Rserv.c:3358: warning: ignoring return value of ‘chdir’, declared with attribute warn_unused_result
Rserv.c: At top level:
Rserv.c:388: warning: ‘fork_http’ defined but not used
Rserv.c:403: warning: ‘fork_https’ defined but not used
Rserv.c:418: warning: ‘fork_ws’ defined but not used
Rserv.c: In function ‘Rserve_QAP1_connected’:
Rserv.c:2256: warning: ‘exp’ may be used uninitialized in this function
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c base64.c -o base64.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c http.c -o http.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c md5.c -o md5.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c oc.c -o oc.o
oc.c: In function ‘oc_new’:
oc.c:72: warning: pointer targets in passing argument 1 of ‘sha1hash’ differ in signedness
sha1.h:4: note: expected ‘const char *’ but argument is of type ‘unsigned char *’
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c qap_decode.c -o qap_decode.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c qap_encode.c -o qap_encode.o
qap_encode.c: In function ‘QAP_storeSEXP’:
qap_encode.c:185: warning: unused variable ‘i’
qap_encode.c:203: warning: unused variable ‘i’
qap_encode.c:294: warning: unused variable ‘i’
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c rsio.c -o rsio.o
rsio.c: In function ‘rsio_read_msg’:
rsio.c:159: warning: dereferencing type-punned pointer will break strict-aliasing rules
rsio.c:208: warning: dereferencing type-punned pointer will break strict-aliasing rules
rsio.c: In function ‘rsio_write’:
rsio.c:243: warning: dereferencing type-punned pointer will break strict-aliasing rules
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c session.c -o session.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c sha1.c -o sha1.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c standalone.c -o standalone.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c tls.c -o tls.o
tls.c: In function ‘new_tls’:
tls.c:41: warning: assignment discards qualifiers from pointer target type
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c websockets.c -o websockets.o
websockets.c: In function ‘WS_connected’:
websockets.c:111: warning: unused variable ‘s’
websockets.c: In function ‘WS_recv_data’:
websockets.c:634: warning: unused variable ‘more’
websockets.c: At top level:
rserr.h:20: warning: ‘RSEprintf’ defined but not used
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -DRSERVE_PKG -I. -Iinclude   -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c winembed.c -o winembed.o
gcc -m64 -std=gnu99 -shared -L/usr/lib64/R/lib -L/usr/local/lib64 -o Rserve.so RSserver.o Rserv.o base64.o http.o md5.o oc.o qap_decode.o qap_encode.o rsio.o session.o sha1.o standalone.o tls.o websockets.o winembed.o -lssl -lcrypto -ldl -lcrypt -L/usr/lib64/R/lib -lR
/usr/bin/ld: /usr/local/lib64/libssl.a(s23_srvr.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib64/libssl.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
make: *** [Rserve.so] Error 1
ERROR: compilation failed for package ‘Rserve’
* removing ‘/home/R/x86_64-redhat-linux-gnu-library/3.2/Rserve’
Warning in install.packages :
  installation of package ‘/usr/lib64/R/library/Rserve_1.7-3.tar.gz’ had non-zero exit status

**Comment by ppiotrow** [comment]
Try installing openSSL.

**Comment by s-u** [comment]
You are linking against static OpenSSL (`/usr/local/lib64/libssl.a`) that was not compiled with `-fPIC`. You have to either install dynamically compiled OpenSSL or re-compiled the static version using `--with-pic`.

**Comment by ayjung** [comment]
[root@ Rserve]# rpm -qa | grep openssl
openssl-1.0.0-20.el6_2.5.x86_64

# cd /usr/lib64/R/library/Rserve
# ./configure CFLAGS=-fPIC or ./configure CFLAGS=--with-pic
OK
 
# cd ./src/client/java/Makefile
# make
javac -d . -source 1.4 -target 1.4 MutableREXP.java package-info.java REngineCallbacks.java REngineConsoleHistoryInterface.java REngineEvalException.java REngineException.java REngineInputInterface.java REngine.java REngineOutputInterface.java REngineStdOutput.java REngineUIInterface.java REXPDouble.java REXPEnvironment.java REXPExpressionVector.java REXPFactor.java REXPGenericVector.java REXPInteger.java REXP.java REXPJavaReference.java REXPLanguage.java REXPList.java REXPLogical.java REXPMismatchException.java REXPNull.java REXPRaw.java REXPReference.java REXPS4.java REXPString.java REXPSymbol.java REXPUnknown.java REXPVector.java REXPWrapper.java RFactor.java RList.java
warning: [options] bootstrap class path not set in conjunction with -source 1.4
warning: [options] source value 1.4 is obsolete and will be removed in a future release
warning: [options] target value 1.4 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
4 warnings
jar fc REngine.jar org
rm -rf org
javac -d . -cp REngine.jar Rserve/package-info.java Rserve/RConnection.java Rserve/RFileInputStream.java Rserve/RFileOutputStream.java Rserve/RserveException.java Rserve/RSession.java Rserve/protocol/jcrypt.java Rserve/protocol/REXPFactory.java Rserve/protocol/RPacket.java Rserve/protocol/RTalk.java
Note: Rserve/protocol/REXPFactory.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
jar fc Rserve.jar org
rm -rf org

# cd ./src/client/java/Rserve/Makefile
# make
javac -d . -cp ../REngine.jar package-info.java RConnection.java RFileInputStream.java RFileOutputStream.java RserveException.java RSession.java protocol/jcrypt.java protocol/REXPFactory.java protocol/RPacket.java protocol/RTalk.java
Note: protocol/REXPFactory.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
jar fc Rserve.jar org
rm -rf org

# cd ./src/client/java/Rserve/test/Makefile
# make

javac -encoding utf8 -source 1.4 -target 1.4 -d . -cp ../Rserve.jar:../../REngine.jar:. test.java
warning: [options] bootstrap class path not set in conjunction with -source 1.4
warning: [options] source value 1.4 is obsolete and will be removed in a future release
warning: [options] target value 1.4 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: test.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
4 warnings
java -cp ../Rserve.jar:../../REngine.jar:. test
org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused
javac -encoding utf8 -source 1.4 -target 1.4 -d . -cp ../Rserve.jar:../../REngine.jar:. PlotDemo.java
warning: [options] bootstrap class path not set in conjunction with -source 1.4
warning: [options] source value 1.4 is obsolete and will be removed in a future release
warning: [options] target value 1.4 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
4 warnings
javac -encoding utf8 -source 1.4 -target 1.4 -d . -cp ../Rserve.jar:../../REngine.jar:. StartRserve.java
warning: [options] bootstrap class path not set in conjunction with -source 1.4
warning: [options] source value 1.4 is obsolete and will be removed in a future release
warning: [options] target value 1.4 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
4 warnings

# cd ./src/client/java/JRI/Makefile
# make
JRIEngine.java:117: error: cannot find symbol
        public Rengine getRni() {
               ^
  symbol:   class Rengine
  location: class JRIEngine
JRIEngine.java:137: error: cannot find symbol
        public JRIEngine(String args[], RMainLoopCallbacks callbacks) throws REngineException {
                                        ^
  symbol:   class RMainLoopCallbacks
  location: class JRIEngine
JRIEngine.java:185: error: cannot find symbol
        public JRIEngine(String args[], RMainLoopCallbacks callbacks, boolean runREPL) throws REngineException {
                                        ^
  symbol:   class RMainLoopCallbacks
  location: class JRIEngine
JRIEngine.java:218: error: cannot find symbol
        public JRIEngine(Rengine eng) throws REngineException {
                         ^
  symbol:   class Rengine
  location: class JRIEngine
JRIEngine.java:787: error: cannot find symbol
        public void   rWriteConsole (Rengine re, String text, int oType) {
                                     ^
  symbol:   class Rengine
  location: class JRIEngine
JRIEngine.java:792: error: cannot find symbol
        public void   rBusy         (Rengine re, int which) {
                                     ^
  symbol:   class Rengine
  location: class JRIEngine
JRIEngine.java:797: error: cannot find symbol
        public synchronized String rReadConsole  (Rengine re, String prompt, int addToHistory) {
                                                  ^
  symbol:   class Rengine
  location: class JRIEngine
JRIEngine.java:805: error: cannot find symbol
        public void   rShowMessage  (Rengine re, String message) {
                                     ^
  symbol:   class Rengine
  location: class JRIEngine
JRIEngine.java:810: error: cannot find symbol
        public String rChooseFile   (Rengine re, int newFile) {
                                     ^
  symbol:   class Rengine
  location: class JRIEngine
JRIEngine.java:816: error: cannot find symbol
        public void   rFlushConsole (Rengine re) {
                                     ^
  symbol:   class Rengine
  location: class JRIEngine
JRIEngine.java:821: error: cannot find symbol
        public void   rSaveHistory  (Rengine re, String filename) {
                                     ^
  symbol:   class Rengine
  location: class JRIEngine
JRIEngine.java:826: error: cannot find symbol
        public void   rLoadHistory  (Rengine re, String filename) {
                                     ^
  symbol:   class Rengine
  location: class JRIEngine
JRIEngine.java:114: error: reference to JRIEngine is ambiguous
                return jriEngine = new JRIEngine(args, callbacks, runREPL);
                                   ^
  both constructor JRIEngine(String[],REngineCallbacks,boolean) in JRIEngine and constructor JRIEngine(String[],RMainLoopCallbacks,boolean) in JRIEngine match
JRIEngine.java:124: error: reference to JRIEngine is ambiguous
                this(new String[] { "--no-save" }, (REngineCallbacks) null, false);
                ^
  both constructor JRIEngine(String[],REngineCallbacks,boolean) in JRIEngine and constructor JRIEngine(String[],RMainLoopCallbacks,boolean) in JRIEngine match
JRIEngine.java:130: error: reference to JRIEngine is ambiguous
                this(args, (REngineCallbacks) null, false);
                ^
  both constructor JRIEngine(String[],REngineCallbacks,boolean) in JRIEngine and constructor JRIEngine(String[],RMainLoopCallbacks,boolean) in JRIEngine match
JRIEngine.java:149: error: cannot find symbol
                if (!Rengine.jriLoaded)
                     ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:152: error: cannot find symbol
                if (Rengine.getVersion() < requiredAPIversion)
                    ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:157: error: cannot find symbol
                rni = new Rengine(args, runREPL, (callbacks == null) ? null : this);
                          ^
  symbol:   class Rengine
  location: class JRIEngine
JRIEngine.java:165: error: cannot find symbol
                        globalEnv = new REXPReference(this, new Long(rni.rniSpecialObject(Rengine.SO_GlobalEnv)));
                                                                                          ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:166: error: cannot find symbol
                        nullValueRef = new REXPReference(this, new Long(R_NilValue = rni.rniSpecialObject(Rengine.SO_NilValue)));
                                                                                                          ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:167: error: cannot find symbol
                        emptyEnv = new REXPReference(this, new Long(rni.rniSpecialObject(Rengine.SO_EmptyEnv)));
                                                                                         ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:168: error: cannot find symbol
                        baseEnv = new REXPReference(this, new Long(rni.rniSpecialObject(Rengine.SO_BaseEnv)));
                                                                                        ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:170: error: cannot find symbol
                        R_UnboundValue = rni.rniSpecialObject(Rengine.SO_UnboundValue);
                                                              ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:188: error: cannot find symbol
                if (!Rengine.jriLoaded)
                     ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:191: error: cannot find symbol
                if (Rengine.getVersion() < requiredAPIversion)
                    ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:194: error: cannot find symbol
                rni = new Rengine(args, runREPL, callbacks);
                          ^
  symbol:   class Rengine
  location: class JRIEngine
JRIEngine.java:202: error: cannot find symbol
                        globalEnv = new REXPReference(this, new Long(rni.rniSpecialObject(Rengine.SO_GlobalEnv)));
                                                                                          ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:203: error: cannot find symbol
                        nullValueRef = new REXPReference(this, new Long(R_NilValue = rni.rniSpecialObject(Rengine.SO_NilValue)));
                                                                                                          ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:204: error: cannot find symbol
                        emptyEnv = new REXPReference(this, new Long(rni.rniSpecialObject(Rengine.SO_EmptyEnv)));
                                                                                         ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:205: error: cannot find symbol
                        baseEnv = new REXPReference(this, new Long(rni.rniSpecialObject(Rengine.SO_BaseEnv)));
                                                                                        ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:207: error: cannot find symbol
                        R_UnboundValue = rni.rniSpecialObject(Rengine.SO_UnboundValue);
                                                              ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:221: error: cannot find symbol
                if (!Rengine.jriLoaded)
                     ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:230: error: cannot find symbol
                        globalEnv = new REXPReference(this, new Long(rni.rniSpecialObject(Rengine.SO_GlobalEnv)));
                                                                                          ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:231: error: cannot find symbol
                        nullValueRef = new REXPReference(this, new Long(R_NilValue = rni.rniSpecialObject(Rengine.SO_NilValue)));
                                                                                                          ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:232: error: cannot find symbol
                        emptyEnv = new REXPReference(this, new Long(rni.rniSpecialObject(Rengine.SO_EmptyEnv)));
                                                                                         ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:233: error: cannot find symbol
                        baseEnv = new REXPReference(this, new Long(rni.rniSpecialObject(Rengine.SO_BaseEnv)));
                                                                                        ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:235: error: cannot find symbol
                        R_UnboundValue = rni.rniSpecialObject(Rengine.SO_UnboundValue);
                                                              ^
  symbol:   variable Rengine
  location: class JRIEngine
JRIEngine.java:771: error: package org.rosuda.JRI does not exist
                        org.rosuda.JRI.REXP rx = rni.createRJavaRef( o );
                                      ^
44 errors
4 warnings
make: *** [JRIEngine.jar] Error 1


# cd ./src/client/java/JRI/test/Makefile
# make
javac -source 1.4 -target 1.4 -classpath ../../REngine.jar:../JRIEngine.jar:/usr/lib64/R/library/rJava/java/boot:/usr/lib64/R/library/rJava/jri/JRI.jar RTest.java
warning: [options] bootstrap class path not set in conjunction with -source 1.4
warning: [options] source value 1.4 is obsolete and will be removed in a future release
warning: [options] target value 1.4 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
RTest.java:291: error: package org.rosuda.REngine.JRI does not exist
                                } else if (!(eng instanceof org.rosuda.REngine.JRI.JRIEngine)) {
                                                                                  ^
RTest.java:308: error: package org.rosuda.REngine.JRI does not exist
                                        REXPReference ref = ((org.rosuda.REngine.JRI.JRIEngine)eng).createRJavaRef( null );
                                                                                    ^
RTest.java:316: error: package org.rosuda.REngine.JRI does not exist
                                        ref = ((org.rosuda.REngine.JRI.JRIEngine)eng).createRJavaRef( p );
                                                                      ^
3 errors
4 warnings
make: *** [RTest.class] Error 1

# cd ./src/client/cxx/Makefile
# make

g++  -DHAVE_CONFIG_H   demo1.cc   -o demo1
/tmp/ccwRpL8G.o: In function `main':
demo1.cc:(.text+0x5b1): undefined reference to `Rconnection::Rconnection(char const*, int)'
demo1.cc:(.text+0x5df): undefined reference to `Rconnection::connect()'
demo1.cc:(.text+0x6e8): undefined reference to `Rconnection::assign(char const*, Rexp*)'
demo1.cc:(.text+0x721): undefined reference to `Rconnection::eval(char const*, int*, int)'
demo1.cc:(.text+0x75f): undefined reference to `Rexp::attribute(char const*)'
demo1.cc:(.text+0x8f1): undefined reference to `Rconnection::assign(char const*, Rexp*)'
demo1.cc:(.text+0x92a): undefined reference to `Rconnection::eval(char const*, int*, int)'
demo1.cc:(.text+0x97d): undefined reference to `Rvector::byName(char const*)'
/tmp/ccwRpL8G.o: In function `Rinteger::Rinteger(int*, int)':
demo1.cc:(.text._ZN8RintegerC2EPii[_ZN8RintegerC5EPii]+0x37): undefined reference to `Rexp::Rexp(int, char const*, int, Rexp*)'
demo1.cc:(.text._ZN8RintegerC2EPii[_ZN8RintegerC5EPii]+0x4e): undefined reference to `Rinteger::fix_content()'
demo1.cc:(.text._ZN8RintegerC2EPii[_ZN8RintegerC5EPii]+0x61): undefined reference to `Rexp::~Rexp()'
/tmp/ccwRpL8G.o: In function `Rdouble::Rdouble(double*, int)':
demo1.cc:(.text._ZN7RdoubleC2EPdi[_ZN7RdoubleC5EPdi]+0x37): undefined reference to `Rexp::Rexp(int, char const*, int, Rexp*)'
demo1.cc:(.text._ZN7RdoubleC2EPdi[_ZN7RdoubleC5EPdi]+0x4e): undefined reference to `Rdouble::fix_content()'
demo1.cc:(.text._ZN7RdoubleC2EPdi[_ZN7RdoubleC5EPdi]+0x61): undefined reference to `Rexp::~Rexp()'
/tmp/ccwRpL8G.o: In function `Rdouble::~Rdouble()':
demo1.cc:(.text._ZN7RdoubleD2Ev[_ZN7RdoubleD5Ev]+0x1f): undefined reference to `Rexp::~Rexp()'
/tmp/ccwRpL8G.o: In function `Rinteger::~Rinteger()':
demo1.cc:(.text._ZN8RintegerD2Ev[_ZN8RintegerD5Ev]+0x1f): undefined reference to `Rexp::~Rexp()'
/tmp/ccwRpL8G.o:(.rodata._ZTV7Rdouble[vtable for Rdouble]+0x28): undefined reference to `Rexp::store(char*)'
/tmp/ccwRpL8G.o:(.rodata._ZTV8Rinteger[vtable for Rinteger]+0x28): undefined reference to `Rexp::store(char*)'
/tmp/ccwRpL8G.o:(.rodata._ZTI7Rdouble[typeinfo for Rdouble]+0x10): undefined reference to `typeinfo for Rexp'
/tmp/ccwRpL8G.o:(.rodata._ZTI8Rinteger[typeinfo for Rinteger]+0x10): undefined reference to `typeinfo for Rexp'
collect2: ld returned 1 exit status
make: *** [demo1] Error 1



> library("Rserve")
Error in library("Rserve") : ?쁒serve??is not a valid installed package

**Comment by s-u** [comment]
Please read R documentation on how to install an R package. It's none of what you're doing above. 

The error with PIC is in SSL, *not* Rserve - please consider reading the first reply I posted.
