### ISSUE TITLE
Version 1.7.3 reliable source

### ISSUE THREAD

**Issue by ppiotrow** [s-u/Rserve#44]
I wonder if there is difference between file Rserve_1.7-3.tar.gz - latest stable version - downloaded from bellow sources.
http://www.rforge.net/Rserve/snapshot/
https://cran.r-project.org/src/contrib/
As you may see they have different modification dates and checksum.

**Comment by s-u** [comment]
CRAN is modifying submitted packages by adding additional field in the DESCRIPTION file so CRAN versions are different from the submitted original.
