### ISSUE TITLE
Cannot install Rserve, clang error

### ISSUE THREAD

**Issue by lazarillo** [s-u/Rserve#45]
Using just R (not RStudio), I tried

    install.packages("Rserve")

I received a handful of warnings (3 of them), but only one error:

    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [server] Error 1
    ERROR: compilation failed for package ‘Rserve’
    * removing ‘/usr/local/lib/R/3.2/site-library/Rserve’

-----

If the warnings are useful:

 1. clang -I/usr/local/Cellar/r/3.2.2_1/R.framework/Resources/include -DNDEBUG -I/usr/local/include -DRSERVE_PKG -I. -Iinclude   -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include  -I/usr/local/include   -fPIC  -g -O2  -c Rserv.c -o Rserv.o

    Rserv.c:2976:16: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
                                        if (fbufl < 0) fbufl = sfbufSize;

 2. clang -I/usr/local/Cellar/r/3.2.2_1/R.framework/Resources/include -DNDEBUG -I/usr/local/include -DRSERVE_PKG -I. -Iinclude   -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include  -I/usr/local/include   -fPIC  -g -O2  -c oc.c -o oc.o

    oc.c:72:11: warning: passing 'unsigned char [64]' to parameter of type 'const char *' converts between pointers to
      integer types with different sign [-Wpointer-sign]
        sha1hash(rbuf, sizeof(rbuf) - 1, hash);

    ./sha1.h:4:27: note: passing argument to parameter 'buf' here
    void sha1hash(const char *buf, int len, unsigned char hash[20]);

 3. clang -DSTANDALONE_RSERVE -DDAEMON -I. -Iinclude -I/usr/local/Cellar/r/3.2.2_1/R.framework/Resources/include -DNDEBUG -I/usr/local/include -DRSERVE_PKG -I. -Iinclude   -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include  -I/usr/local/include   -fPIC  -g -O2  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include -g -O2  -DRSERVE_PKG -I. -Iinclude    -o Rserve standalone.c md5.c session.c qap_decode.c qap_encode.c sha1.c base64.c websockets.c RSserver.c tls.c http.c oc.c rsio.c -ldl    -F/usr/local/Cellar/r/3.2.2_1/R.framework/.. -framework R -lintl -Wl,-framework -Wl,CoreFoundation -ldl  

    In file included from standalone.c:6:
    ./Rserv.c:2976:16: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
                                        if (fbufl < 0) fbufl = sfbufSize;

    oc.c:72:11: warning: passing 'unsigned char [64]' to parameter of type 'const char *' converts between pointers to
      integer types with different sign [-Wpointer-sign]
        sha1hash(rbuf, sizeof(rbuf) - 1, hash);

    ./sha1.h:4:27: note: passing argument to parameter 'buf' here
    void sha1hash(const char *buf, int len, unsigned char hash[20]);

-----

Here are some software & computer specs:

Mac:

    System Software Overview:

      System Version:	OS X 10.11.1 (15B42)
      Kernel Version:	Darwin 15.0.0
      Boot Volume:	Macintosh HD
      Boot Mode:	Normal
      Computer Name:	Mike's Mac
      User Name:	Mike Williamson (mike)
      Secure Virtual Memory:	Enabled
      Time since boot:	3 days 2:11

R:

    > R.Version()
    $platform
    [1] "x86_64-apple-darwin15.0.0"

    $`svn rev`
    [1] "69053"

    $version.string
    [1] "R version 3.2.2 (2015-08-14)"

    $nickname
    [1] "Fire Safety"

-----

Thanks!

**Comment by lazarillo** [comment]
Sorry!  I had searched for a while to see what the problem was, but could not find anyhting.

I tried again, and finally did find a solution which resolved it [on StackExchange](http://stackoverflow.com/questions/24620879/error-while-starting-rserve-on-mac-os-x-maverick) (the solution talking about installing `Rserve` outside of R itself, via the `R CMD INSTALL ...` command.

So this is not a bug (at least not on `Rserve`'s side), but I'm leaving it in case others have this same trouble.

**Comment by s-u** [comment]
That SO post makes no sense - it's completely bogus (deprecation warnings are not errors). Also you reported only the last part of the error but not the actual error why the linking failed - you stripped that rather important information. Finally  you seem to be mixing Homebrew with other 3rd party libraries - that is most certainly something you do at your own risk assuming that you know what you're doing - I wouldn't be surprised if that breaks horribly. If in doubt, install clean R from CRAN - that is supported and Rserve builds against that out of the box.

**Comment by lazarillo** [comment]
Wow!  I had posted the error complete and in detail.  There were no intelligible errors, only the error I had posted.  I also provided any pertinent OS + software concerns.  I had then also provided the warnings, recognizing they weren't useful, but also recognizing the true error had no information in it.

-----

Then I had resolved the issue myself, stated as much, and provided a pointer to the solution that worked for me and may work for others.  I marked the issue as closed myself, left the issue up, to be helpful, because it has clearly happened to at least 2 people.  Yet, the reaction I get is far more emotional than helpful.  I don't understand the vitriol.

**Comment by s-u** [comment]
I have no idea what you're referring to  - the answer was purely factual - the most important information was in the piece that you didn't find "intelligible" which is why it's important that you post the full error - but you certainly did not post "the error complete and in detail".

Your resolution didn't actually solve the problem - it just uses something entirely different than what you asked about (and even that is just a guess since you didn't actually tell us what you did). Therefore it is irrelevant to the posted question here. The SO post was apparently answered by someone with no idea about the issue since the statements are false so it's certainly not helpful. The question there also lacked the error output entirely so we can't even say if it is in any way related.

To use an analogy, it's like reporting to a car manufacturer that your car stopped working and then reporting you solved it by buying another car since a friend told you buying a car fixed the issue of his car not working. So buy a new car is the solution. In reality you friend didn't realize he has to put gas in it while your car's battery was not charged, but there is no way to tell the difference from what you said since both of you just reported that the car stopped working.
