### ISSUE TITLE
Need Updated Documentation

### ISSUE THREAD

**Issue by sbryfcz** [s-u/Rserve#50]
I've noticed some great work has gone into RServe over the past few years but I feel like the documentation has not been kept up very well. For example, the New/Changelog shows some great stuff for 1.8-3 (I think). But I dont really understand what these things are:

What does a Rserve.context() actually do? Could we get an example? 

"added WebSockets/QAP proxy and HTTP server. It is a stand-alone program that can be used to separate the R process from the network to enhance security" Are these 2 different things? Or one new feature? How do I start this stand-alone program? HOW can I use it to enhance security? It looks like maybe it starts automatically but its not really clear. An example would be great.

As someone who is trying to champion my company in using R and specifically RServe for some of our applications, I'd love to have a bit better documentation.  Thanks for all that you do.

**Comment by s-u** [comment]
It is one process that can do both. Depending on your start-up options it acts as WebSocket QAP tunnel (using a dedicated WebSockets port set via `-w`) and/or as a HTTP server (serving both static and dynamic content on the port set by `-p`) which also allows WebSocket upgrade to create the tunnel. The point is that you run QAP on a local socket so you can easily set permissions (whereas using a TCP port allows no access control).

`Rserver.context()` is a way to define/retrieve a random identifier for the current evaluation context. When you use asynchronous communication (OOB messages), you need a way to figure out at what point was that message created during the evaluation, so you can nest evaluations and still know where it came from. The same is true for errors. For example, in [RCloud](http://rcloud.social) there is an outer context - if anything goes wrong in that context we know it's our internal code. Then when we evaluate cells, we do that in a new context - that way we know that the error came from the user code and not the system itself.

**Comment by s-u** [comment]
This is now documented in the [OCAP entry of the Wiki](https://github.com/s-u/Rserve/wiki/OCAP-mode)
