### ISSUE TITLE
Is rserve interrupt working for Windows?

### ISSUE THREAD

**Issue by maxyeg** [s-u/Rserve#52]
Hi!
I'd like to confirm if rserve can be interrupted(not killed) in windows properly.
I've searched your repository for `SIGINT` occurrences and see some expressions like `#ifdef unix`.
I'm not sure but maybe rserve won't handle `SIGINT` in windows?

I start rserve by `run.Rserve(...)` and it will be interrupted in unix if needed using: `kill -SIGINT pid`.

**Comment by s-u** [comment]
Windows doesn't support unix signals. I'm not aware of a corresponding facility on Windows. Their idea of "signals" is intra-process only. There are ways in which you can enter R on idle (e.g. by running a parallel thread with its own window context and issuing a Win32 message - see the `background` package), but have not tried to use it for this purpose. Given how of little use and limited is Windows with R computing, Rserve doesn't try to implement anything Windows-specific in this regard.
