### ISSUE TITLE
respond with 101 Switching Protocols on websocket upgrade

### ISSUE THREAD

**Issue by gordonwoodhull** [s-u/Rserve#53]
Just for kicks, I'm checking whether Microsoft Edge (currently the most standards-compliant browser haha) works with RCloud.

The first problem I'm running into is that the response to the websocket upgrade seems to be incorrect. Apparently Rserve still tries to serve the requested path and responds with the corresponding http response.

Typically people will request an url like `ws://domain.com:8080/websocket`

According to [this random bug report](https://bugs.eclipse.org/bugs/show_bug.cgi?id=405831) (too lazy to read the spec myself, sorry),

> RFC-6455 ... specifies that the server should response with 
> HTTP/1.1 101 Switching Protocols
> (http://tools.ietf.org/html/rfc6455#section-1.3)

Instead Rserve responds with 200 if the path specifies an existing file, and 404 otherwise. Edge's WebSocket implementation then barfs with

```
WebSocket Error: Incorrect HTTP response. Status code 200, OK
```

I'm not sure if it's worthwhile to address this since probably something else won't work, but I thought I'd report this in case it's easy to fix. 

Searching for the error message above will turn up various discussions claiming that Microsoft is right about this one (if pedantic) and Firefox and Chrome's implementations are too lenient.

**Comment by s-u** [comment]
Rserve *does* respond with 101 to WS upgrade. If you see anything else then the request is not recognized as an attempt to upgrade. I suspect that IE may be sending some trailing junk such that it doesn't look like a valid upgrade to websockets on the Rserve side. Would it be possible to get the full request packet that IE sends so we can see why it doesn't look like a WS upgrade request?
