### ISSUE TITLE
asInteger[] may make an Integer Overlow

### ISSUE THREAD

**Issue by johnny-bui** [s-u/Rserve#55]
This is my code:
``` java
final RConnection c = new RConnection();
String makeIntOverflow = "makeIntOverflow <- function(x){" +
				"	abshauf <- table(x);" +
				"	lg <- length(abshauf);" +
				"	refheuf <- abshauf / lg;" +
				"	mydata <- c(abshauf, refheuf);" +
				"	dim(mydata) <- c(lg,2); " +
				"	mydata <- data.frame(table(x), mydata); " +
				"	return (mydata); " +
			"}" ;
c.eval(makeIntOverflow);
REXP eval = c.eval("makeIntOverflow( c(1,1,1,1,1,0,0,0) );");
REXP rowName = eval.getAttribute("row.names");
int[] asInt = rowName.asIntegers();
for (int i = 0; i < asInt.length ; ++i){
	System.out.print(asInt[i]+"\n");
}
```
As I execute the R-Code directly in R, as 
```R
makeIntOverflow <- function (){....}
makeIntOverflow( c(1,1,1,1,1,0,0,0) );
```
I get the row name as "1" and "2".
As I execute the above Java code, I get the rowNames as an ``int[]`` of ``{-2147483648, -2}``, which is
obviously not expected. Have you may by an  workaround for this?
(-2147483648 = -2^31)

**Comment by s-u** [comment]
It is expected - short row name representation in R is `c(NA_integer, -nrows)`

**Comment by johnny-bui** [comment]
A Silly question: How can I convert them (-2147483648, -2) in a human-understandable format (1, 2) elegantly?

**Comment by s-u** [comment]
Well, what it tells you is that the row names is not set and that there are `-isInt[1]` rows. How you deal with that is entirely up to your application code. If you really want a `String[]` array then you can naively create one with a  `for` loop.

**Comment by johnny-bui** [comment]
Thank for your hints, it works well for me.
