### ISSUE TITLE
eval command by SEXP(XT_CLOS) returns null

### ISSUE THREAD

**Issue by ksobue** [s-u/Rserve#57]
When CMD_eval command is executed with "function(a = 'hello', b = 2) { rep(a, b) }" text string, it returns SEXP object as follows.

            {
                type: _.XT_CLOS,
                value: {
                    formals: {
                        type: _.XT_LIST_TAG,
                        value: [
                            {
                                type: _.XT_ARRAY_STR,
                                value: ["hello"]
                            },
                            {
                                type: _.XT_SYMNAME,
                                value: "a"
                            },
                            {
                                type: _.XT_ARRAY_DOUBLE,
                                value: [2]
                            },
                            {
                                type: _.XT_SYMNAME,
                                value: "b"
                            }
                        ]
                    },
                    body: {
                        type: _.XT_LANG_NOTAG,
                        value: [
                            {
                                type: _.XT_SYMNAME,
                                value: "{"
                            },
                            {
                                type: _.XT_LANG_NOTAG,
                                value: [
                                    {
                                        type: _.XT_SYMNAME,
                                        value: "rep"
                                    },
                                    {
                                        type: _.XT_SYMNAME,
                                        value: "a"
                                    },
                                    {
                                        type: _.XT_SYMNAME,
                                        value: "b"
                                    }
                                ]
                            }
                        ]
                    }
                }
            }

But when another eval command is executed with this SEXP object, then the result is null. I expected the same SEXP object to be returned, which is the behavior when other expression types are used.

**Comment by s-u** [comment]
I'm not quite sure I follow. I'm not sure but I suspect that you may be talking about sending closures from the client to the server. Closures are purely informational, because there is no way in Rserve to send environments (since they are reference-semantics objects). So you can retrieve closures on the client side to see their form, but they cannot be pushed back to R since representation on the client side is incomplete and not a valid closure in R. Therefore closures ignored when parsing QAPs from the client to the server. Is that what you were asking about?

**Comment by ksobue** [comment]
If closures are informational only, then the returning null makes sense. I am creating node.js client and have been testing if the eval command are returning same sexp for string input and sexp input, and found this. Thanks for the detail explanation, I understand closures cannot be pushed back and it is different from other types. Thanks!

**Comment by s-u** [comment]
FWIW there is a "offical" node.js client maintained by us at https://github.com/att/rserve-js
