### ISSUE TITLE
Rserve logs

### ISSUE THREAD

**Issue by jangorecki** [s-u/Rserve#61]
Is there any place where Rserve can store it's logs? as the regular server application.
Searching for "log" does not find anything in documentation, faq, technical info. No luck in `R CMD Rserve --help` too. It could be any logs, errors from Rserve sessions or a logs from Rserve daemon itself.

**Comment by sebastian-c** [comment]
One way to log would simply be to capture the stdout:

    R CMD Rserve > Rserve.log 2>&1

**Comment by rtanas** [comment]
Is there any other way to log? Is there an access log similar to apache or nginx

**Comment by saurabh321gupta** [comment]
hey @rtanas  did you find any way to log ?? kindly share the solution if you found any.

**Comment by feilx** [comment]
@rtanas @saurabh321gupta you can use tryCatch to capture R error logs, and use other software to write logs.

**Comment by s-u** [comment]
Rserve uses the standard syslog-compatible protocol which can be configured using the `ulog` directive in the config file. It supports unix sockets, UDP and TCP. The current logging is mostly focused on OCAP mode.
