### ISSUE TITLE
Could we close RServe in R? 

### ISSUE THREAD

**Issue by Lvnszn** [s-u/Rserve#65]
Hi, 
The question show as title. Rconnection could be closed in Java, but Rserve couldn't be closed.
Is there a solution about it?

**Comment by s-u** [comment]
Can you clarify? Did you try `RS.close()`? Which client/package are you using?

**Comment by Lvnszn** [comment]
Sorry for my ambiguous describe. The Rserve was opened in linux OS, and I want to close it in linuxOS. Looks like the process was only closed with command "kill -9 PID".

**Comment by s-u** [comment]
`kill -9` is somewhat drastic. It's still entirely unclear what your'e talking about - are you talking about the server process (which can be shutdown using the shutdown command or by sending `SIGINT`) or a client session? The latter is collected by closing the client connection (see above).
