### ISSUE TITLE
Rserver textual output using sink command

### ISSUE THREAD

**Issue by mas-dude** [s-u/Rserve#66]
Is it safe to use the sink command to capture output from R in RServer? Is each request completely isolated so that each sink connection would be independent? (there is a warning in the sink documentation about reusing connections so was just wondering how it might be affected when run within RServer).

**Comment by s-u** [comment]
Yes, each session is an independent R process so there should be no issues on behalf of Rserve.

**Comment by mas-dude** [comment]
Thanks.
