### ISSUE TITLE
(null).1001.1001: Cannot open file '', reason No such file or directory

### ISSUE THREAD

**Issue by woodvi** [s-u/Rserve#69]
I posted a couple times to StackOverflow about what appears to be a bug in Rserve used in particular cases.  

http://stackoverflow.com/questions/30512972/error-in-plot-new-when-creating-pdf-in-r/34774826#34774826
http://stackoverflow.com/questions/34883386/what-is-folder-null-1001-1001

Calls to plot.new() get an error message "Cannot open file '', reason No such file or directory", which seems to depend on a mysterious folder named (null).1001.1001

**Comment by s-u** [comment]
Can you elaborate how this has anything to do with Rserve? Rserve doesn't create any such directory - you're likely taking about R's `tempdir()` so you may want to read up on it in R documentation and ways to handle it in R. AFAICS all of the above has something to do with `knitr`, no `Rserve`.

**Comment by danpritts** [comment]
I ran into this today - upon startup with /etc/init.d/rserve start, a directory '(null).91.91' is created in the cwd of the user running the init script.  91 is the gid and uid specified in /etc/rserve.conf.  

I'm sitting on an old version.  Using RHEL6 with the EPEL build of R 3.5.0-3 and Rserve 1.7-3.  

rserve.conf contains:

```
uid 91
gid 91
workdir /var/rservework
```
