### ISSUE TITLE
fork(.)here is not working

### ISSUE THREAD

**Issue by TrlInfab** [s-u/Rserve#72]
Hello,

I just cannot get the parameter `fork.here` in the Rserv.cfg file to do its job. Also I am not quiet sure how the parameter is corectly spelled.

[Here](http://rforge.net/Rserve/news.html) as well as [here](https://mailman.rz.uni-augsburg.de/pipermail/stats-rosuda-devel/2014q4/002156.html) it is stated that it is spelled `fork here`

On the [github wikipage](https://github.com/s-u/Rserve/wiki/rserve.conf) it is stated that you should use the parameter `fork.here`. Well I didn't succed with neither of those. I used this config-file

```
remote enable

eval library('jsonlite'); load("model")

source Score.R

port 6311
fork.here
port 6312
```

Everything works fine. Libraries loaded, model loaded, remote access enabled, but I only get 1 running Service with the port 6312. Could someone point out what I am doing wrong?

**Comment by s-u** [comment]
Thanks, I have fixed the Wiki entry. The directive is `fork` with `here` as the only valid parameter hence `fork here` is the line in the config file. Please replace `fork.here` with `fork here` above and see if it works as expected. (Note that forking is only supported on unix, not Windows).

**Comment by TrlInfab** [comment]
I tried that and it did not work for me.

I used this command to start the server on a CentOS distribution:
`R CMD Rserve --silent --gui-none --vanilla --RS-conf /home/Rserve/Rserv.cfg`

**Comment by TrlInfab** [comment]
Just wanted to update that everything is working as intended with `fork here`. It was my failure. I didn't make sure that Rserve was removed completely before updating to 1.8-5. Thus, some of the old 1.7-3 version remained on the server not supporting the feature.
