### ISSUE TITLE
Update version on CRAN?

### ISSUE THREAD

**Issue by longouyang** [s-u/Rserve#73]
If I'm understanding things correctly, CRAN has version 1.7-3, whereas the latest is 1.8-5. Could you update the CRAN version?

**Comment by artemklevtsov** [comment]
> Rserve 1.8-0 released on RForge.net. We are currently restricting the 1.8 series to RForge releases (i.e., CRAN still has 1.7) because some applications may rely on control commands which are currently unsupported in the 1.8 series due to a large overhaul of the communication between the master server and the sessions. All other features are considered stable in the 1.8 series. If you don't require control commands (or don't know what it is) then we strongly recommend installing the latest 1.8 version.
