### ISSUE TITLE
Rserve not able to share object

### ISSUE THREAD

**Issue by vawanipati** [s-u/Rserve#76]
I have created a Pool of connection 5 Rserve and using in 8 core machine,
I want to call Rserve and load a object(xyz.RDA), vai a function prediction() which contains below sample code
```
 if(!exists("models"))
{
  print("started")
 load(file = model path)    # path xyz.RDA
  print("ended end")
}
```
Now this code works for consecutive request from java, It loads the RDA once but when I started running it parallel it try to load every time for second connection.

My expectation is the load should not happen for every connection, can it be achieved or I am doing some wrong configuration
I created Rserve using only **Rserve(port="63111")**

**Comment by s-u** [comment]
All connections are independent (that's the whole point!). If you want to pre-load data/packages, you can only do that at startup using the `source`  or `eval` configuration directives.
