### ISSUE TITLE
plen is too large

### ISSUE THREAD

**Issue by selvavm** [s-u/Rserve#88]
I installed Rserve from CRAN in a linux ec2 instance. I am trying to connect using Tableau from my local desktop.

I am getting intermittantly connection error, like, 1 in 5 connection fails. Below is the Rserve console output when the connection is unsuccessful,

`header read result: 16
DUMP [16]: 50 4f 53 54 20 2f 65 76 61 6c 75 61 74 65 20 48  |POST /evaluate H
WARNING: discarding buffer because too big (awaiting 5197265520862506784 bytes)`

**Comment by s-u** [comment]
Whatever is doing the request send HTTP instead of QAP:

```
> rawToChar(as.raw(c(0x50,0x4f,0x53,0x54,0x20,0x2f,0x65,0x76,0x61,0x6c,0x75,0x61,0x74,0x65,0x20,0x48)))
[1] "POST /evaluate H"
```

so that's a bug in the client (Tableau?).

**Comment by DavidDurston** [comment]
Was there ever a solution discovered to this? Getting the same thing, but would find it hard to believe Tableau is the cause of the error and it going unnoticed.

**Comment by s-u** [comment]
Contact Tableau support - like I said Rserve has nothing to do with it, because some client is using HTTP to talk to it instead of the QAP1 Rserve protocol (in the case reported above). Hence I cannot do anything about it as it's something on the client side, not Rserve.
