### ISSUE TITLE
Install.packages(<package>)

### ISSUE THREAD

**Issue by VivekKumarNeu** [s-u/Rserve#93]
Hi All,

Does Rserve in cpp supports installation of any package in R or it assumes that the package is already installed. I am asking this because I tried installing a package and the code just hung. I do not get response from Rconnection->eval(...).

Thanks.

**Comment by s-u** [comment]
Rserve is just R so it does. However, make sure you're not expecting user input - i.e. make sure you have set the `repos` and all required parameters. If in doubt, check the Rserve console to see what R is doing.

**Comment by VivekKumarNeu** [comment]
Thanks Simon. I was missing the repos parameter. 
And, when the package is installed , it is for only that current session or It will be installed permanently in R package?

**Comment by s-u** [comment]
Regular R rules apply - by default it's system-wide, assuming you have sufficient rights.
