### ISSUE TITLE
Project Wiki is editable by anyone

### ISSUE THREAD

**Issue by tomjorquera** [s-u/Rserve#97]
Hi,

It seems the project wiki is (as for many other github projects) editable by anyone.

I just stumbled into this by accidentally reverting [the conf page](https://github.com/s-u/Rserve/wiki/rserve.conf) to an earlier version while looking at its history (I reverted my revert right away).

To fix this you can restrict wiki edition to project collaborators in the settings (see [the github doc](https://help.github.com/articles/changing-access-permissions-for-wikis/) but check the option instead of unchecking it of course).

Sorry for the noise !

**Comment by s-u** [comment]
Thanks for reverting it. The idea is that anyone can collaborate and update the wiki, so we have to live with the fact that vandals abuse it. However, you have also proven that the faith in open community is well founded since you were the good citizen who fixed it.
