### ISSUE TITLE
Authentication when using http/https protocol

### ISSUE THREAD

**Issue by dselivanov** [s-u/Rserve#98]
Hi Simon. As I understand when using http protocol `Rserve` ignores authentication part of the configuration (`pwdfile`, `auth`, `cachepwd`, `plaintext`). So authentication should be part of the user code - header check.  Is it correct? If so will it make sense to add the http/https authentication to `Rserve` side?

**Comment by s-u** [comment]
Correct, the authentication relates to `QAP`, not `http`.
