### ISSUE TITLE
[bug?] http over TLS doesn't work on OS X

### ISSUE THREAD

**Issue by dselivanov** [s-u/Rserve#99]
Hi Simon. I've discovered strange `Rserve` (1.8-5) behaviour on OS X (10.13.2) - it seems http with TLS doesn't work.
Consider following simple example. We start `Rserve` with following configuration
```
source http.R

http.tls.port 8002
tls.key server.key
tls.cert server.cert

encoding utf8
port 6311
```
Where `http.R` is just:
```r
.http.request = function(url, query, body, headers) list("pong", "text/plain", "", 200L)
```
and certificates can be obtained with 
```
openssl req \
  -newkey rsa:2048 \
  -x509 \
  -nodes \
  -keyout server.key \
  -new \
  -out server.cert \
  -subj /CN=localhost \
  -sha256 \
  -days 3650
```

So at the end we start `Rserve` with
```
R CMD Rserve --RS-conf Rserve.conf 
```

Now strange things start:

1. `curl --insecure -v https://localhost:8002/ping` hangs after first handshake:
	  ```
	*   Trying 127.0.0.1...
	* TCP_NODELAY set
	* Connected to localhost (127.0.0.1) port 8002 (#0)
	* ALPN, offering h2
	* ALPN, offering http/1.1
	* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
	* successfully set certificate verify locations:
	*   CAfile: /etc/ssl/cert.pem
	  CApath: none
	* TLSv1.2 (OUT), TLS handshake, Client hello (1):
	```
1. **HTTP WORKS**, but we didn't requested for that in configuration! `curl http://localhost:8002/ping` returns `pong`.

**On Linux (ubuntu 16.04) however everything works fine (can query using https and plain http is disabled).**

**Comment by s-u** [comment]
It looks like you didn't build `Rserve` with SSL support. Check the output of the installation.
